<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title> Data Wrangling </title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Data Wrangling_files/libs/clipboard/clipboard.min.js"></script>
<script src="Data Wrangling_files/libs/quarto-html/quarto.js"></script>
<script src="Data Wrangling_files/libs/quarto-html/popper.min.js"></script>
<script src="Data Wrangling_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Data Wrangling_files/libs/quarto-html/anchor.min.js"></script>
<link href="Data Wrangling_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Data Wrangling_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Data Wrangling_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Data Wrangling_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Data Wrangling_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="style.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Outline</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span style="color: #2C6D26;"><strong>Introduction</strong></span></a>
  <ul class="collapse">
  <li><a href="#tibbles" id="toc-tibbles" class="nav-link" data-scroll-target="#tibbles"><span style="color: #002D62;">Tibbles</span></a></li>
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import"><span style="color: #002D62;">Data Import</span></a></li>
  <li><a href="#tidy-data" id="toc-tidy-data" class="nav-link" data-scroll-target="#tidy-data"><span style="color: #002D62;">Tidy Data</span></a></li>
  </ul></li>
  <li><a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples"><span style="color: #2C6D26;"><strong>Examples</strong></span></a>
  <ul class="collapse">
  <li><a href="#data-frame" id="toc-data-frame" class="nav-link" data-scroll-target="#data-frame"><span style="color: #002D62;">Data Frame</span></a></li>
  <li><a href="#the-tidyverse-package" id="toc-the-tidyverse-package" class="nav-link" data-scroll-target="#the-tidyverse-package"><span style="color: #002D62;">The tidyverse package</span></a></li>
  <li><a href="#data-import-1" id="toc-data-import-1" class="nav-link" data-scroll-target="#data-import-1"><span style="color: #002D62;"><strong>Data Import</strong></span></a></li>
  <li><a href="#data-transformation" id="toc-data-transformation" class="nav-link" data-scroll-target="#data-transformation"><span style="color: #002D62;">Data Transformation</span></a>
  <ul class="collapse">
  <li><a href="#filter" id="toc-filter" class="nav-link" data-scroll-target="#filter"><strong>Filter</strong></a></li>
  <li><a href="#arrange" id="toc-arrange" class="nav-link" data-scroll-target="#arrange"><strong>Arrange</strong></a></li>
  <li><a href="#select" id="toc-select" class="nav-link" data-scroll-target="#select"><strong>Select</strong></a></li>
  <li><a href="#add-new-variable" id="toc-add-new-variable" class="nav-link" data-scroll-target="#add-new-variable"><strong>Add New Variable</strong></a></li>
  <li><a href="#summarize" id="toc-summarize" class="nav-link" data-scroll-target="#summarize"><strong>Summarize</strong></a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values"><strong>Missing values</strong></a></li>
  <li><a href="#count" id="toc-count" class="nav-link" data-scroll-target="#count"><strong>Count</strong></a></li>
  <li><a href="#factors" id="toc-factors" class="nav-link" data-scroll-target="#factors"><strong>Factors</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#pivoting" id="toc-pivoting" class="nav-link" data-scroll-target="#pivoting"><span style="color: #2C6D26;"><strong>Pivoting</strong></span></a>
  <ul class="collapse">
  <li><a href="#pivot-longer" id="toc-pivot-longer" class="nav-link" data-scroll-target="#pivot-longer"><span style="color:#002D62;"><strong>Pivot Longer</strong></span></a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span style="color: #002D62;"><strong>Example</strong></span></a></li>
  <li><a href="#pivot-wider" id="toc-pivot-wider" class="nav-link" data-scroll-target="#pivot-wider"><span style="color: #2C6D26;"><strong>Pivot Wider</strong></span></a></li>
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"><span style="color: #002D62;"><strong>Example</strong></span></a></li>
  </ul></li>
  <li><a href="#combining-tables" id="toc-combining-tables" class="nav-link" data-scroll-target="#combining-tables"><span style="color: #2C6D26;"><strong>Combining Tables</strong></span></a>
  <ul class="collapse">
  <li><a href="#left-join" id="toc-left-join" class="nav-link" data-scroll-target="#left-join"><span style="color: #002D62;"><strong>Left Join</strong></span></a></li>
  <li><a href="#right-join" id="toc-right-join" class="nav-link" data-scroll-target="#right-join"><span style="color: #002D62;"><strong>Right Join</strong></span></a></li>
  <li><a href="#inner-join" id="toc-inner-join" class="nav-link" data-scroll-target="#inner-join"><span style="color: #002D62;"><strong>Inner Join</strong></span></a></li>
  <li><a href="#full-join" id="toc-full-join" class="nav-link" data-scroll-target="#full-join"><span style="color: #002D62;"><strong>Full join</strong></span></a></li>
  </ul></li>
  <li><a href="#creating-groups" id="toc-creating-groups" class="nav-link" data-scroll-target="#creating-groups"><span style="color: #2C6D26;"><strong>Creating Groups</strong></span></a></li>
  <li><a href="#strings" id="toc-strings" class="nav-link" data-scroll-target="#strings"><span style="color: #2C6D26;"><strong>Strings</strong></span></a>
  <ul class="collapse">
  <li><a href="#exercise" id="toc-exercise" class="nav-link" data-scroll-target="#exercise"><span style="color: #2C6D26;"><strong>Exercise</strong></span></a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><p style="color:black,text-align:center"><br>
Data Wrangling<br>
</p></h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><font color="#ff6600"><b>Biometrics Unit</b></font> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <font color="#ff6600"><b>International Institute of Tropical Agriculture (IITA)</b></font>
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1><span style="color: #2C6D26;"><strong>Introduction</strong></span></h1>
<p>Data wrangling is the process of transforming raw data into a more organized and structured format, which facilitates improved insights and better decision-making. Imagine your data as a set of puzzle you need to solve, data wrangling is a tool that will significantly help you to organise the data, making it much easier to solve the data puzzles.</p>
<p>There are six stages involved in data wrangling, they are highlighted below:</p>
<ol type="1">
<li><p><strong>Data Discovery:</strong> Data discovery is the <em>process of uncovering and exploring valuable insights</em> within data. This usually involves collecting data from different sources, transforming and merging it, and employing visualization and analytical methods to reveal patterns, trends, and insights. The aim is to make data more accessible and actionable for decision-making, enabling users to grasp complex information and address specific business questions.</p>
<p>Data discovery is the process that enables users to visually explore data and apply advanced analytics to uncover patterns, gain insights, answer specific questions, and extract value from business information. It involves integrating and transforming data from multiple sources, analyzing data structures, and using visualization techniques to gain insights and extract valuable information.</p></li>
<li><p><strong>Data Structuring:</strong> Data structures are specialized formats for organizing data on a computer to ensure efficient processing, storage, and retrieval. They provide a systematic way to manage information, making it easier to access and use. A data structure is a <em>method for organizing and managing data</em>. It helps in gathering different types of data, whether structured or unstructured, and transforming it into useful and meaningful information. An array is an example of data structure.</p></li>
<li><p><strong>Data Cleaning:</strong> Data cleaning is a vital stage in the data science workflow, focusing on <em>detecting and rectifying errors, inconsistencies, and inaccuracies in the data to enhance its quality and usability</em>. This process is crucial because raw data often contains noise, gaps, and inconsistencies that can adversely affect the <em>accuracy and dependability</em> of the insights generated from it. Data cleaning involves preparing data for analysis by <em>correcting or eliminating data that is incorrect, incomplete, irrelevant, duplicated, or poorly formatted</em>. It involves steps such as <em>removing unwanted observations, managing structure errors, managing unwanted outliers and handling missing data</em>.</p></li>
<li><p><strong>Data Enriching:</strong> After transforming your data into a more usable format, evaluate whether you have all the necessary information for your analysis. If not, you can enhance it by incorporating values from additional datasets. This is also a good time to consider adding metadata to your database.</p></li>
<li><p><strong>Data validation:</strong> Once you’ve converted your data into a more usable format, assess if you have all the information required for your analysis. If anything is missing, you can augment it by integrating data from other sources. Additionally, this is an opportune moment to add metadata to your database. Validation <em>guarantees the quality and reliability of your processed data.</em> It involves checking for inconsistencies, verifying data integrity, and ensuring the data meets predefined standards. This process helps build confidence in the dataset’s accuracy and ensures it is suitable for meaningful analysis.</p></li>
<li><p><strong>Data Publishing:</strong> Data publishing refers to the process of making data available to users, often by sharing or disseminating it through various platforms or channels. This can involve publishing datasets on websites, data repositories, or databases, <em>ensuring that the data is accessible, usable, and properly documented for others to analyze or utilize.</em></p>
<p>Also, there are three main aspect of data wrangling. These includes:</p>
<ol type="1">
<li>Tibbles</li>
<li>Data import</li>
<li>Tidy data</li>
</ol></li>
</ol>
<section id="tibbles" class="level2">
<h2 class="anchored" data-anchor-id="tibbles"><span style="color: #002D62;">Tibbles</span></h2>
<p>Tibbles are a key feature of the tidyverse, distinguishing it from most other R packages, which typically use standard data frames. You can convert a dataset to tibbles with <code>as_tibble()</code></p>
<p><strong>Example</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)  <span class="co">#load tidyverse package</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agridat)  <span class="co">#load agridat package</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> (australia.soybean)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(dat)  <span class="co">#convert dataframe to tibble</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;fct&gt; &lt;fct&gt; &lt;int&gt; &lt;fct&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 454 more rows</code></pre>
</div>
</div>
<p><br><br></p>
<p>You can create tibbles from raw data using <code>tibble()</code> as shown below</p>
<p><strong>Example</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">x =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="at">y =</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">2</span>), <span class="at">z =</span> x <span class="sc">+</span> y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
       x     y     z
   &lt;int&gt; &lt;int&gt; &lt;int&gt;
 1     1     1     2
 2     2     2     4
 3     3     3     6
 4     4     4     8
 5     5     5    10
 6     6     1     7
 7     7     2     9
 8     8     3    11
 9     9     4    13
10    10     5    15</code></pre>
</div>
</div>
<p><br><br></p>
<p><strong>What are the common differences between a tibble and a dataframe</strong></p>
<p>A tibble is considered a neater format of a data frame and its often used in tidyverse and ggplot2 packages. Tibble has an advanced print function and only shows the first ten rows with all the columns fitted on the screen. The data type is written just below the heading of each column. This does not apply to data frame. Tibble can be used for indexing such as $, [[ ]]. $ extracts using name while [[ ]] extract by name and position.</p>
<p><strong>Example</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">234</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">runif</span>(<span class="dv">5</span>), <span class="at">y =</span> <span class="fu">rnorm</span>(<span class="dv">5</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract by name</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>x</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.74562000 0.78171242 0.02003711 0.77608539 0.06691009</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df[[<span class="st">"x"</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.74562000 0.78171242 0.02003711 0.77608539 0.06691009</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract by position</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df[[<span class="dv">1</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.74562000 0.78171242 0.02003711 0.77608539 0.06691009</code></pre>
</div>
</div>
<p><br><br></p>
</section>
<section id="data-import" class="level2">
<h2 class="anchored" data-anchor-id="data-import"><span style="color: #002D62;">Data Import</span></h2>
<p><strong>Importing a Comma Seperated Version (CSV)</strong></p>
<p>Data import can be done with the <code>readr</code> package which is a core <code>tidyverse</code> package. This is used for reading data stored in text file spreadsheets into R. Some readr’s function are used in turning flat files into dataframe. You can load readr using the code <code>library(readr)</code>, this gives you access to functions such as: <code>read_csv()</code> for reading comma delimited files, <code>read_csv2()</code> for semicolon separated files, <code>read_table</code> for white space separated values etc.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install readr package</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"readr"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># load the package</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># read the csv file into a tibble</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"steptoe.morex.pheno.csv"</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,432 × 10
   gen     env   amylase diapow hddate lodging  malt height protein yield
   &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 Steptoe MN92     22.7     46   150.      NA  73.6   84.5    10.5  5.53
 2 Steptoe MTi92    30.1     72   178       10  76.5   NA      11.2  8.64
 3 Steptoe MTd92    26.7     78   165       15  74.5   75.5    13.4  5.90
 4 Steptoe ID91     26.2     74   179       NA  74.1  111      12.1  8.63
 5 Steptoe OR91     19.6     62   191       NA  71.5   90      11.7  5.34
 6 Steptoe WA91     23.6     54   181       NA  73.8  112      10    6.27
 7 Steptoe MTi91    21       62   181       NA  70.8   98      12    4.10
 8 Steptoe MTd91    NA       NA   181       NA  NA     82      NA    7.07
 9 Steptoe NY92     NA       NA   176        0  NA     77.5    NA    6.05
10 Steptoe ON92     NA       NA   198       50  NA     95      NA    3.70
# ℹ 2,422 more rows</code></pre>
</div>
</div>
<p><br><br></p>
<p><strong>Importing an Excel Version (XLSL)</strong></p>
<p>The readxl library can also be assessed from the readr package and it is used to import excel files. The functions to import excel files are <code>read_excel()</code> or <code>read_xlsx()</code>. The <code>read_excel()</code> auto detect the format while <code>read_xlsl()</code>permits more than two sheets in a file.</p>
<p><strong>Example</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install the readxl package install.packages('readxl')</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># load the readxl package</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the Excel file into a tibble</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sugar cane.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"Sugar cane"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 6
   Choice Stalks Height Diameter  Cane Variety
    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1      1     23   2.37     1.7  12.4        2
 2      0     11   2.25     1.68  5.49       3
 3      0      9   2.5      1.93  6.59       2
 4      1     25   2.4      2.12 21.2        2
 5      1     20   2.5      1.7  11.4        1
 6      0     12   1.9      1.51  4.08       1
 7      0     12   1.7      1.34  2.88       3
 8      1     16   2.4      1.84 10.2        1
 9      0      4   2.4      2.11  3.36       3
10      1     11   2.35     2     8.12       1
# ℹ 20 more rows</code></pre>
</div>
</div>
<p><br><br></p>
</section>
<section id="tidy-data" class="level2">
<h2 class="anchored" data-anchor-id="tidy-data"><span style="color: #002D62;">Tidy Data</span></h2>
<p>Tidy data considers ways to convert your messy dataset into format that are clean and can be easily analysed. The aim of tidyr is to assist in creating tidy data, where:</p>
<ul>
<li>Each variable is represented as a column, and each column corresponds to a variable.</li>
<li>Each observation is represented as a row, and each row corresponds to an observation.</li>
<li>Each value is contained within a cell, with each cell holding a single value.</li>
</ul>
<p>The principles of tidy data offer a standardized method for organizing data values within a dataset. The tidy data standard is designed to ease the initial exploration and analysis of data and to streamline the creation of data analysis tools that integrate seamlessly.</p>
<p>Various functions can be used in the tidyr package, functions such as <em>pivoting (longer and wider), rectangling, nesting, splitting, replace and drop na</em> etc.</p>
</section>
</section>
<section id="examples" class="level1">
<h1><span style="color: #2C6D26;"><strong>Examples</strong></span></h1>
<section id="data-frame" class="level2">
<h2 class="anchored" data-anchor-id="data-frame"><span style="color: #002D62;">Data Frame</span></h2>
<p><strong>Let’s create a data frame</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>trial01 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">variety =</span> <span class="fu">c</span>(<span class="st">"G01-US234"</span>, <span class="st">"G05-BT456"</span>, <span class="st">"Ind01"</span>, <span class="st">"G11-DR234"</span>,</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Check"</span>), <span class="at">yield =</span> <span class="fu">c</span>(<span class="fl">6323.3</span>, <span class="fl">2515.2</span>, <span class="dv">5611</span>, <span class="dv">7729</span>, <span class="fl">7843.25</span>), <span class="at">height =</span> <span class="fu">c</span>(<span class="fl">123.3</span>, <span class="fl">95.2</span>,</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="dv">113</span>, <span class="fl">89.45</span>, <span class="fl">145.67</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Let’s display the data frame</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>trial01  <span class="do">## display the object in Q2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety   yield height
1 G01-US234 6323.30 123.30
2 G05-BT456 2515.20  95.20
3     Ind01 5611.00 113.00
4 G11-DR234 7729.00  89.45
5     Check 7843.25 145.67</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(trial01)  <span class="do">## display the object in Q1</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co"># trial01[R,C]</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>trial01[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety   yield height
1 G01-US234 6323.30 123.30
2 G05-BT456 2515.20  95.20
3     Ind01 5611.00 113.00
4 G11-DR234 7729.00  89.45
5     Check 7843.25 145.67</code></pre>
</div>
</div>
<p><br><br></p>
<p><strong>We can extract the first three rows:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># object[1:nrows, 1:ncolumns]</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>trial01[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety   yield height
1 G01-US234 6323.30 123.30
2 G05-BT456 2515.20  95.20
3     Ind01 5611.00 113.00
4 G11-DR234 7729.00  89.45
5     Check 7843.25 145.67</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>trial01[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, ]  <span class="co"># the three first rows and all columns</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety  yield height
1 G01-US234 6323.3  123.3
2 G05-BT456 2515.2   95.2
3     Ind01 5611.0  113.0</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can extract the first two columns</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>trial01[, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety   yield
1 G01-US234 6323.30
2 G05-BT456 2515.20
3     Ind01 5611.00
4 G11-DR234 7729.00
5     Check 7843.25</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can extract 'from 3rd to 5th row' with '2nd and 3rd column'</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>trial01[<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    yield height
3 5611.00 113.00
4 7729.00  89.45
5 7843.25 145.67</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>trial01[, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety height
1 G01-US234 123.30
2 G05-BT456  95.20
3     Ind01 113.00
4 G11-DR234  89.45
5     Check 145.67</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can list the column names using any of this methods</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(trial01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "variety" "yield"   "height" </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(trial01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "variety" "yield"   "height" </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can extract specific column from a data frame using column name trial01$</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>yield1 <span class="ot">&lt;-</span> trial01<span class="sc">$</span>yield</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>trial01<span class="sc">$</span>yield</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6323.30 2515.20 5611.00 7729.00 7843.25</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># trial01$Yield. R is case sensitive, yield is different from Yield</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># We can find the mean of the extracted column using any of the codes below</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(trial01<span class="sc">$</span>yield)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6004.35</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(yield1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6004.35</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(trial01<span class="sc">$</span>yield)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6004.35</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We can add a column vector using a new column name</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>trial01<span class="sc">$</span>flowering <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">87</span>, <span class="dv">101</span>, <span class="dv">88</span>, <span class="dv">120</span>, <span class="dv">90</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>trial01<span class="sc">$</span>flowering <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">87</span>, <span class="dv">101</span>, <span class="dv">88</span>, <span class="dv">120</span>, <span class="dv">90</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>trial01</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety   yield height flowering
1 G01-US234 6323.30 123.30        87
2 G05-BT456 2515.20  95.20       101
3     Ind01 5611.00 113.00        88
4 G11-DR234 7729.00  89.45       120
5     Check 7843.25 145.67        90</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>flowering2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">87</span>, <span class="dv">101</span>, <span class="dv">88</span>, <span class="dv">120</span>, <span class="dv">90</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>trial01<span class="sc">$</span>flowerin2 <span class="ot">&lt;-</span> flowering2</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>trial01</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety   yield height flowering flowerin2
1 G01-US234 6323.30 123.30        87        87
2 G05-BT456 2515.20  95.20       101       101
3     Ind01 5611.00 113.00        88        88
4 G11-DR234 7729.00  89.45       120       120
5     Check 7843.25 145.67        90        90</code></pre>
</div>
</div>
<p><br><br></p>
</section>
<section id="the-tidyverse-package" class="level2">
<h2 class="anchored" data-anchor-id="the-tidyverse-package"><span style="color: #002D62;">The tidyverse package</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>trial01</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    variety   yield height flowering flowerin2
1 G01-US234 6323.30 123.30        87        87
2 G05-BT456 2515.20  95.20       101       101
3     Ind01 5611.00 113.00        88        88
4 G11-DR234 7729.00  89.45       120       120
5     Check 7843.25 145.67        90        90</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let's look at the structure of trial01</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(trial01)  <span class="do">## structure of trial01: what's trial01?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   5 obs. of  5 variables:
 $ variety  : chr  "G01-US234" "G05-BT456" "Ind01" "G11-DR234" ...
 $ yield    : num  6323 2515 5611 7729 7843
 $ height   : num  123.3 95.2 113 89.5 145.7
 $ flowering: num  87 101 88 120 90
 $ flowerin2: num  87 101 88 120 90</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can convert trial01 to a tibble and save the new created object into</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># trial01.tibble</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>trial01.new <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(trial01)</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>trial01.new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 5
  variety   yield height flowering flowerin2
  &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1 G01-US234 6323.  123.         87        87
2 G05-BT456 2515.   95.2       101       101
3 Ind01     5611   113          88        88
4 G11-DR234 7729    89.4       120       120
5 Check     7843.  146.         90        90</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dbl(double) and int(integer) are numeric</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="data-import-1" class="level2">
<h2 class="anchored" data-anchor-id="data-import-1"><span style="color: #002D62;"><strong>Data Import</strong></span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read csv file: supply the path to a file and you get the data into R</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>mydata <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"C:/Users/DOjekere/CGIAR/Fowobaje, Kayode Rapheal (IITA) - Training Materials/2024/R/RMD Training/Example-02.csv"</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>mydata</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 454 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># If a project/working directory is created and we are working within the</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># project,</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>mydata1 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Example-02.csv"</span>)  <span class="co"># Tab keyboard</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Read xlsx file</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>iwu <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"C:/Users/DOjekere/CGIAR/Fowobaje, Kayode Rapheal (IITA) - Training Materials/2024/R/RMD Training/Example-03.xlsx"</span>,</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sheet =</span> <span class="st">"whitecorn"</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Read Excel file:</span></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>mydata2 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Example-03.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"whitecorn"</span>)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(mydata2)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>mydata2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 540 × 9
   loc          gen       yield stand rootlodge stalklodge earht flower moisture
   &lt;chr&gt;        &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;
 1 Knoxville,TN AgriGold…  138.  91.1         0        0    47.3   67.3     21.7
 2 Knoxville,TN AgriGold…  151   86.1         0        0.6  45     67.7     21.5
 3 Knoxville,TN Asgrow_X…  140.  94.4         0        0.6  46.3   67       19.8
 4 Knoxville,TN Beck_Ex2…  190.  90           0        0    57     67.3     19.4
 5 Knoxville,TN Crows_W54  141.  88.9         0        0.6  47     68.7     21.1
 6 Knoxville,TN Crows_W55  139.  88.9         0        1.2  52     66.7     20  
 7 Knoxville,TN Crows_EX…  179.  88.9         0        0.7  47     67.3     20.2
 8 Knoxville,TN Crows_EX…  180   94.4         0        1.8  49     67.7     19.9
 9 Knoxville,TN Dekalb_D…  166.  98.9         0        0.6  47     67       21.3
10 Knoxville,TN Dekalb_D…  169.  99.4         0        1.1  37     65.3     19.1
# ℹ 530 more rows</code></pre>
</div>
</div>
</section>
<section id="data-transformation" class="level2">
<h2 class="anchored" data-anchor-id="data-transformation"><span style="color: #002D62;">Data Transformation</span></h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>example02 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Example-02.csv"</span>)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>example02</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 454 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(example02)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "env"     "loc"     "year"    "gen"     "yield"   "height"  "lodging"
 [8] "size"    "protein" "oil"    </code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(example02)  <span class="do">## really don't need when you have tibble</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>spc_tbl_ [464 × 10] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ env    : chr [1:464] "L70" "L70" "L70" "L70" ...
 $ loc    : chr [1:464] "Lawes" "Lawes" "Lawes" "Lawes" ...
 $ year   : num [1:464] 1970 1970 1970 1970 1970 1970 1970 1970 1970 1970 ...
 $ gen    : chr [1:464] "G01" "G02" "G03" "G04" ...
 $ yield  : num [1:464] 2.39 2.28 2.57 2.88 2.39 ...
 $ height : num [1:464] 1.45 1.45 1.46 1.26 1.33 ...
 $ lodging: num [1:464] 4.25 4.25 3.75 3.5 3.5 4 3 3.25 3 3.75 ...
 $ size   : num [1:464] 8.45 9.95 10.85 10.05 11 ...
 $ protein: num [1:464] 36.7 37.5 37.8 38.5 37.5 ...
 $ oil    : num [1:464] 20.9 20.7 21.3 22 22.1 ...
 - attr(*, "spec")=
  .. cols(
  ..   env = col_character(),
  ..   loc = col_character(),
  ..   year = col_double(),
  ..   gen = col_character(),
  ..   yield = col_double(),
  ..   height = col_double(),
  ..   lodging = col_double(),
  ..   size = col_double(),
  ..   protein = col_double(),
  ..   oil = col_double()
  .. )
 - attr(*, "problems")=&lt;externalptr&gt; </code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># I want to display the number of years</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(example02<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1970 1970 1970 1970 1970 1970</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(example02<span class="sc">$</span>year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1970 1971</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(example02<span class="sc">$</span>loc)  <span class="co"># having the number of locations </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lawes"      "Brookstead" "Nambour"    "RedlandBay"</code></pre>
</div>
</div>
<p><br><br></p>
<p><strong>The pipe |&gt;</strong></p>
<p>Pipes are a powerful tool for clearly expressing a sequence of multiple operations. Object |&gt; (object is usually a tibble, a data) Function(argument1, argument2, …)</p>
<section id="filter" class="level3">
<h3 class="anchored" data-anchor-id="filter"><strong>Filter</strong></h3>
<p>We can filter the data for 1970</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>example02<span class="fl">.70</span> <span class="ot">&lt;-</span> example02 <span class="sc">|&gt;</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">1970</span>)</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>example02<span class="fl">.70</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 222 more rows</code></pre>
</div>
</div>
<p>Filtering using the pipe is equivalent to below but not nice</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>example02.<span class="fl">70.</span>not.nice <span class="ot">&lt;-</span> example02[example02<span class="sc">$</span>year <span class="sc">==</span> <span class="dv">1970</span>, ]</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>example02.<span class="fl">70.</span>not.nice</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 222 more rows</code></pre>
</div>
</div>
<p>We can filter the data for one location :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>example02.Lawes <span class="ot">&lt;-</span> example02 <span class="sc">|&gt;</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(loc <span class="sc">==</span> <span class="st">"Lawes"</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>example02.Lawes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 116 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 106 more rows</code></pre>
</div>
</div>
<p>We can filter the data with multiple criteria (several arguments)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>example02.Lawes3<span class="fl">.2</span> <span class="ot">&lt;-</span> example02 <span class="sc">|&gt;</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(yield <span class="sc">&gt;</span> <span class="fl">3.2</span>, loc <span class="sc">==</span> <span class="st">"Lawes"</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>example02.Lawes3<span class="fl">.2</span> <span class="ot">&lt;-</span> example02 <span class="sc">|&gt;</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(yield <span class="sc">&gt;</span> <span class="fl">3.2</span>, loc <span class="sc">==</span> <span class="st">"Brookstead"</span> <span class="sc">|</span> loc <span class="sc">==</span> <span class="st">"Lawes"</span>)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>example02.Lawes3<span class="fl">.2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 17 × 10
   env   loc         year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes       1970 G26    3.21  1.18     4     9.55    39.8  20.1
 2 L70   Lawes       1970 G45    3.26  0.785    2.75 23.2     37    23.7
 3 L70   Lawes       1970 G48    4.38  0.76     3.75 18.8     38.2  24.4
 4 L70   Lawes       1970 G50    3.38  0.835    2.75 17.9     39.9  24.6
 5 L71   Lawes       1971 G45    3.82  0.56     1.25 19.6     36.3  23.7
 6 L71   Lawes       1971 G48    3.57  0.545    1.25 17.0     39.1  24.1
 7 L71   Lawes       1971 G49    3.44  0.66     1.25 18.6     37.5  23.1
 8 L71   Lawes       1971 G57    3.39  0.685    1.5  19.4     38.6  22.8
 9 B71   Brookstead  1971 G45    3.75  0.735    2.5  23.6     37.9  22.1
10 B71   Brookstead  1971 G46    3.37  0.735    2.75 18.1     38.3  20.5
11 B71   Brookstead  1971 G47    3.45  0.725    1.75 20.7     39.6  23.2
12 B71   Brookstead  1971 G49    3.90  1.00     2.25 21.6     37.5  22.2
13 B71   Brookstead  1971 G50    3.61  0.75     3    19.3     40.2  23.3
14 B71   Brookstead  1971 G53    3.82  0.675    1.75 21.9     39.0  22.1
15 B71   Brookstead  1971 G55    3.48  0.57     1.25 20.0     41.6  21.9
16 B71   Brookstead  1971 G56    3.54  0.69     1.25 21.4     41.0  22.1
17 B71   Brookstead  1971 G57    3.58  0.635    1.25 22.9     41.4  21.7</code></pre>
</div>
</div>
<p>What does the following command do?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(gen <span class="sc">==</span> <span class="st">"G01"</span> <span class="sc">|</span> gen <span class="sc">==</span> <span class="st">"G02"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 10
   env   loc         year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes       1970 G01   2.39   1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes       1970 G02   2.28   1.45     4.25  9.95    37.6  20.7
 3 B70   Brookstead  1970 G01   1.25   1.01     3.25  8.85    39.5  18.8
 4 B70   Brookstead  1970 G02   1.17   1.13     2.75  8.9     38.6  19.8
 5 N70   Nambour     1970 G01   2.26   0.75     2.25  9.25    34.2  22.3
 6 N70   Nambour     1970 G02   2.16   0.71     2     9.35    37.6  22.4
 7 R70   RedlandBay  1970 G01   0.778  0.9      3.25  6.25    40.8  15.9
 8 R70   RedlandBay  1970 G02   1.09   0.9      3.75  7.35    41.0  17.6
 9 L71   Lawes       1971 G01   2.79   0.97     2.5   8.35    39.4  18.7
10 L71   Lawes       1971 G02   2.62   0.785    2.25  9.75    40.6  19.8
11 B71   Brookstead  1971 G01   2.56   0.965    3.25  8.9     40.3  18.2
12 B71   Brookstead  1971 G02   2.34   0.835    2.75 10.9     41.8  18.8
13 N71   Nambour     1971 G01   2.10   0.725    1.25  7.3     38.5  19.3
14 N71   Nambour     1971 G02   2.6    0.595    1     9.45    41.0  20.7
15 R71   RedlandBay  1971 G01   1.18   0.97     2.25  6.75    42.1  16.9
16 R71   RedlandBay  1971 G02   1.90   0.74     1.75  7.95    42.7  18.9</code></pre>
</div>
</div>
</section>
<section id="arrange" class="level3">
<h3 class="anchored" data-anchor-id="arrange"><strong>Arrange</strong></h3>
<p>We can arrange example02 by yield in ascending order</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>example02 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Example-02.csv"</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(yield)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc         year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 N70   Nambour     1970 G58   0.282  0.395    1    17.4     39.2  20.8
 2 R70   RedlandBay  1970 G36   0.365  0.915    3.75  6.15    42.9  14.3
 3 B70   Brookstead  1970 G08   0.385  1.12     2.25  6.15    38.5  17.9
 4 B70   Brookstead  1970 G30   0.424  1.07     2.5   5.75    40.2  16.5
 5 R70   RedlandBay  1970 G11   0.455  1.00     3.5   4       42.9  14.2
 6 B70   Brookstead  1970 G52   0.466  0.56     1.25 10.2     40.4  17.4
 7 B70   Brookstead  1970 G03   0.468  1.16     2.25 10.8     37.8  20.4
 8 R70   RedlandBay  1970 G17   0.487  0.89     3.25  5.65    44.8  13.1
 9 R70   RedlandBay  1970 G12   0.492  1.05     3.25  4.1     41.8  13.9
10 R70   RedlandBay  1970 G31   0.517  0.93     3.5   6.7     42.6  15.6
# ℹ 454 more rows</code></pre>
</div>
</div>
<p>We can arrange example02 by yield in descending order</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc         year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes       1970 G48    4.38  0.76     3.75  18.8    38.2  24.4
 2 R70   RedlandBay  1970 G56    4.13  0.56     2.25  19.0    38    24.0
 3 R71   RedlandBay  1971 G49    4.00  0.905    1.75  17.2    36.6  22.6
 4 B71   Brookstead  1971 G49    3.90  1.00     2.25  21.6    37.5  22.2
 5 L71   Lawes       1971 G45    3.82  0.56     1.25  19.6    36.3  23.7
 6 B71   Brookstead  1971 G53    3.82  0.675    1.75  21.9    39.0  22.1
 7 B71   Brookstead  1971 G45    3.75  0.735    2.5   23.6    37.9  22.1
 8 R70   RedlandBay  1970 G57    3.67  0.545    1.75  16.6    38.2  23.7
 9 R70   RedlandBay  1970 G49    3.62  1.02     3.5   14.2    36.3  23.4
10 B71   Brookstead  1971 G50    3.61  0.75     3     19.3    40.2  23.3
# ℹ 454 more rows</code></pre>
</div>
</div>
<p>We can arrange example02 by year, loc, gen</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(year, loc, gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc         year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 B70   Brookstead  1970 G01   1.25    1.01    3.25  8.85    39.5  18.8
 2 B70   Brookstead  1970 G02   1.17    1.13    2.75  8.9     38.6  19.8
 3 B70   Brookstead  1970 G03   0.468   1.16    2.25 10.8     37.8  20.4
 4 B70   Brookstead  1970 G04   1.44    1.24    1.5  10.6     38.7  20.4
 5 B70   Brookstead  1970 G05   1.34    1.12    2    12.0     37.8  20.8
 6 B70   Brookstead  1970 G06   0.913   1.10    2.25 11       37.4  19.9
 7 B70   Brookstead  1970 G07   1.24    1.13    2    10.2     37.8  20.3
 8 B70   Brookstead  1970 G08   0.385   1.12    2.25  6.15    38.5  17.9
 9 B70   Brookstead  1970 G09   1.11    1.04    1.75  8.3     37.9  20.0
10 B70   Brookstead  1970 G10   1.80    1.04    2    11.8     38.4  19.7
# ℹ 454 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(year), loc, gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc         year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 B71   Brookstead  1971 G01    2.56  0.965    3.25   8.9    40.3  18.2
 2 B71   Brookstead  1971 G02    2.34  0.835    2.75  10.9    41.8  18.8
 3 B71   Brookstead  1971 G03    2.87  0.98     3.25  12.4    39.8  19.6
 4 B71   Brookstead  1971 G04    3.01  0.9      2.25  12.8    38.5  19.5
 5 B71   Brookstead  1971 G05    2.54  0.975    3.25  13.3    39.4  19.9
 6 B71   Brookstead  1971 G06    1.88  0.94     3.25  12.8    37.6  19.6
 7 B71   Brookstead  1971 G07    2.56  0.95     2.75  14      37.4  19.5
 8 B71   Brookstead  1971 G08    1.61  0.915    3     12.3    37.7  19.0
 9 B71   Brookstead  1971 G09    2.24  0.85     2.75  12.0    39.6  18.2
10 B71   Brookstead  1971 G10    2.60  0.81     2.5   13.4    40.0  18.6
# ℹ 454 more rows</code></pre>
</div>
</div>
</section>
<section id="select" class="level3">
<h3 class="anchored" data-anchor-id="select"><strong>Select</strong></h3>
<p>When working with many variables, it can be a good practice to narrow the dataset and consider only few variables for analysis. Let’s only consider the location, year, genotype, yield, and height</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>example02.short <span class="ot">&lt;-</span> example02 <span class="sc">|&gt;</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(loc, year, gen, yield, height)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>example02.short</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 5
   loc    year gen   yield height
   &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1 Lawes  1970 G01    2.39  1.44 
 2 Lawes  1970 G02    2.28  1.45 
 3 Lawes  1970 G03    2.57  1.46 
 4 Lawes  1970 G04    2.88  1.26 
 5 Lawes  1970 G05    2.39  1.34 
 6 Lawes  1970 G06    2.41  1.36 
 7 Lawes  1970 G07    2.70  1.3  
 8 Lawes  1970 G08    2.46  0.955
 9 Lawes  1970 G09    2.57  1.03 
10 Lawes  1970 G10    2.98  1.16 
# ℹ 454 more rows</code></pre>
</div>
</div>
<p>If we are interested in moving a particular variable to the first column in the dataframe, select() and everything() can do that. We can also move more than one variable</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(year, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
    year env   loc   gen   yield height lodging  size protein   oil
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1  1970 L70   Lawes G01    2.39  1.44     4.25  8.45    36.7  20.9
 2  1970 L70   Lawes G02    2.28  1.45     4.25  9.95    37.6  20.7
 3  1970 L70   Lawes G03    2.57  1.46     3.75 10.8     37.8  21.3
 4  1970 L70   Lawes G04    2.88  1.26     3.5  10.0     38.4  22.0
 5  1970 L70   Lawes G05    2.39  1.34     3.5  11       37.5  22.1
 6  1970 L70   Lawes G06    2.41  1.36     4    11.8     38.2  21.2
 7  1970 L70   Lawes G07    2.70  1.3      3    11.8     37.4  21.7
 8  1970 L70   Lawes G08    2.46  0.955    3.25 10       35.2  21.1
 9  1970 L70   Lawes G09    2.57  1.03     3    11.2     35.9  21.5
10  1970 L70   Lawes G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 454 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(year, loc, gen, <span class="fu">everything</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
    year loc   gen   env   yield height lodging  size protein   oil
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1  1970 Lawes G01   L70    2.39  1.44     4.25  8.45    36.7  20.9
 2  1970 Lawes G02   L70    2.28  1.45     4.25  9.95    37.6  20.7
 3  1970 Lawes G03   L70    2.57  1.46     3.75 10.8     37.8  21.3
 4  1970 Lawes G04   L70    2.88  1.26     3.5  10.0     38.4  22.0
 5  1970 Lawes G05   L70    2.39  1.34     3.5  11       37.5  22.1
 6  1970 Lawes G06   L70    2.41  1.36     4    11.8     38.2  21.2
 7  1970 Lawes G07   L70    2.70  1.3      3    11.8     37.4  21.7
 8  1970 Lawes G08   L70    2.46  0.955    3.25 10       35.2  21.1
 9  1970 Lawes G09   L70    2.57  1.03     3    11.2     35.9  21.5
10  1970 Lawes G10   L70    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 454 more rows</code></pre>
</div>
</div>
<p><strong>NOTE:</strong> Select refers to columns: select (yield, loc, gen) – choose the columns arrange refers to rows: arrange(loc, desc(yield)) – sort</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(yield, loc, gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 3
   yield loc   gen  
   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;
 1  2.39 Lawes G01  
 2  2.28 Lawes G02  
 3  2.57 Lawes G03  
 4  2.88 Lawes G04  
 5  2.39 Lawes G05  
 6  2.41 Lawes G06  
 7  2.70 Lawes G07  
 8  2.46 Lawes G08  
 9  2.57 Lawes G09  
10  2.98 Lawes G10  
# ℹ 454 more rows</code></pre>
</div>
</div>
<p>This code will not work because there is no variable named “desc(yield)”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># example02 |&gt; select (loc, gen, desc(yield))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But what we want is:</p>
<pre><code>1. select the three variables, AND
2. sort the yield in desc order</code></pre>
<p>This can be done with:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>new <span class="ot">&lt;-</span> example02 <span class="sc">|&gt;</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">select</span>(loc, gen, yield) <span class="sc">|&gt;</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br></p>
</section>
<section id="add-new-variable" class="level3">
<h3 class="anchored" data-anchor-id="add-new-variable"><strong>Add New Variable</strong></h3>
<p>We can add new columns that are functions of existing columns with <code>mutate()</code> which always adds new columns at the end of the data new column</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>new1 <span class="ot">&lt;-</span> example02.short <span class="sc">|&gt;</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">yield_kg_ha =</span> yield <span class="sc">*</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Replace an existing column</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>new2 <span class="ot">&lt;-</span> example02.short <span class="sc">|&gt;</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">yield =</span> yield <span class="sc">*</span> <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="summarize" class="level3">
<h3 class="anchored" data-anchor-id="summarize"><strong>Summarize</strong></h3>
<p>We can be interested having the mean of yield</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(example02<span class="sc">$</span>yield, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.047427</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>a</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 3 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(a, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="cn">NA</span>)</span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>b</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  2  3  4 NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(b, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(example02)  <span class="co"># summary of the dataframe</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     env                loc                 year          gen           
 Length:464         Length:464         Min.   :1970   Length:464        
 Class :character   Class :character   1st Qu.:1970   Class :character  
 Mode  :character   Mode  :character   Median :1970   Mode  :character  
                                       Mean   :1970                     
                                       3rd Qu.:1971                     
                                       Max.   :1971                     
     yield           height          lodging          size       
 Min.   :0.282   Min.   :0.2500   Min.   :1.00   Min.   : 4.000  
 1st Qu.:1.515   1st Qu.:0.7075   1st Qu.:1.50   1st Qu.: 7.838  
 Median :2.075   Median :0.8875   Median :2.25   Median : 9.500  
 Mean   :2.047   Mean   :0.8831   Mean   :2.31   Mean   :11.138  
 3rd Qu.:2.558   3rd Qu.:1.0450   3rd Qu.:3.00   3rd Qu.:14.050  
 Max.   :4.381   Max.   :1.7300   Max.   :4.75   Max.   :23.600  
    protein           oil       
 Min.   :33.20   Min.   :13.03  
 1st Qu.:38.14   1st Qu.:17.97  
 Median :40.25   Median :19.82  
 Mean   :40.33   Mean   :19.92  
 3rd Qu.:42.20   3rd Qu.:22.09  
 Max.   :48.50   Max.   :26.84  </code></pre>
</div>
</div>
<p><strong>But we prefer using summarize from tidyverse</strong></p>
<p><code>Summarize()</code> collapses a data frame to a single or few row(s)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">yield_mean =</span> <span class="fu">mean</span>(yield, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  yield_mean
       &lt;dbl&gt;
1       2.05</code></pre>
</div>
</div>
<p><strong>Summarize by group</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(example02<span class="sc">$</span>loc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Lawes"      "Brookstead" "Nambour"    "RedlandBay"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb121-2"><a href="#cb121-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(loc) <span class="sc">|&gt;</span></span>
<span id="cb121-3"><a href="#cb121-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">yield_loc =</span> <span class="fu">mean</span>(yield, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  loc        yield_loc
  &lt;chr&gt;          &lt;dbl&gt;
1 Brookstead      2.01
2 Lawes           2.37
3 Nambour         2.09
4 RedlandBay      1.72</code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(loc, year) <span class="sc">|&gt;</span></span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">yield_loc =</span> <span class="fu">mean</span>(yield, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 3
# Groups:   loc [4]
  loc         year yield_loc
  &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;
1 Brookstead  1970      1.56
2 Brookstead  1971      2.46
3 Lawes       1970      2.24
4 Lawes       1971      2.51
5 Nambour     1970      1.89
6 Nambour     1971      2.30
7 RedlandBay  1970      1.64
8 RedlandBay  1971      1.79</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(gen) <span class="sc">|&gt;</span></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">yield =</span> <span class="fu">mean</span>(yield, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb125-4"><a href="#cb125-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 58 × 2
   gen   yield
   &lt;chr&gt; &lt;dbl&gt;
 1 G49    3.22
 2 G48    3.05
 3 G50    2.97
 4 G45    2.91
 5 G57    2.89
 6 G53    2.87
 7 G56    2.82
 8 G47    2.66
 9 G55    2.53
10 G04    2.44
# ℹ 48 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(gen, loc) <span class="sc">|&gt;</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">yield =</span> <span class="fu">mean</span>(yield, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">arrange</span>(<span class="fu">desc</span>(yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 3
# Groups:   gen [58]
   gen   loc        yield
   &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
 1 G48   Lawes       3.98
 2 G49   RedlandBay  3.81
 3 G45   Lawes       3.54
 4 G50   Brookstead  3.39
 5 G53   Brookstead  3.36
 6 G49   Brookstead  3.35
 7 G45   Brookstead  3.27
 8 G57   Lawes       3.26
 9 G50   Lawes       3.24
10 G57   Brookstead  3.20
# ℹ 222 more rows</code></pre>
</div>
</div>
</section>
<section id="missing-values" class="level3">
<h3 class="anchored" data-anchor-id="missing-values"><strong>Missing values</strong></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>missing_dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Example-02-missing.csv"</span>)</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-3"><a href="#cb129-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(missing_dat<span class="sc">$</span>yield, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.044911</code></pre>
</div>
</div>
<p><strong>How to get the missing data if any</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>example02.missing <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Example-02-missing.csv"</span>)</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>missing_dat <span class="sc">|&gt;</span></span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(loc) <span class="sc">|&gt;</span></span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">Nmissing =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(yield)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  loc        Nmissing
  &lt;chr&gt;         &lt;int&gt;
1 Brookstead        0
2 Lawes             2
3 Nambour           1
4 RedlandBay        0</code></pre>
</div>
</div>
<p>Select the obs with a missing yield</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a>missing_dat <span class="sc">|&gt;</span></span>
<span id="cb133-2"><a href="#cb133-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="fu">is.na</span>(yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 10
  env   loc      year gen   yield height lodging  size protein   oil
  &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 L70   Lawes    1970 G29      NA  1.13     4     9.65    39.4  19.9
2 L70   Lawes    1970 G32      NA  1.73     3.5   9.65    42.2  18.7
3 N70   Nambour  1970 G06      NA  0.595    1.25 12.0     35.1  23.2</code></pre>
</div>
</div>
<p>The total number of obs is 464</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a>example02.missing <span class="sc">|&gt;</span></span>
<span id="cb135-2"><a href="#cb135-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 461 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 451 more rows</code></pre>
</div>
</div>
<p>464 obs = 461 valid + 3 missing</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">is.na</span>(example02.missing<span class="sc">$</span>yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(example02.missing<span class="sc">$</span>yield))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
</section>
<section id="count" class="level3">
<h3 class="anchored" data-anchor-id="count"><strong>Count</strong></h3>
<p>Counting the number of observations</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb141-2"><a href="#cb141-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(loc) <span class="sc">|&gt;</span></span>
<span id="cb141-3"><a href="#cb141-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">new4 =</span> <span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  loc         new4
  &lt;chr&gt;      &lt;int&gt;
1 Brookstead   116
2 Lawes        116
3 Nambour      116
4 RedlandBay   116</code></pre>
</div>
</div>
</section>
<section id="factors" class="level3">
<h3 class="anchored" data-anchor-id="factors"><strong>Factors</strong></h3>
<p>The function as.factor() convert a variable to a factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a>example02<span class="sc">$</span>env <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(example02<span class="sc">$</span>env)</span>
<span id="cb143-2"><a href="#cb143-2" aria-hidden="true" tabindex="-1"></a>example02<span class="sc">$</span>loc <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(example02<span class="sc">$</span>loc)</span>
<span id="cb143-3"><a href="#cb143-3" aria-hidden="true" tabindex="-1"></a>example02<span class="sc">$</span>gen <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(example02<span class="sc">$</span>gen)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is equivalent to the code below using mutate() and the pipe |&gt;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb144"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb144-1"><a href="#cb144-1" aria-hidden="true" tabindex="-1"></a>example02 <span class="ot">&lt;-</span> example02 <span class="sc">|&gt;</span></span>
<span id="cb144-2"><a href="#cb144-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">env =</span> <span class="fu">factor</span>(env), <span class="at">loc =</span> <span class="fu">factor</span>(loc), <span class="at">gen =</span> <span class="fu">factor</span>(gen))</span>
<span id="cb144-3"><a href="#cb144-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb144-4"><a href="#cb144-4" aria-hidden="true" tabindex="-1"></a>example02 <span class="sc">|&gt;</span></span>
<span id="cb144-5"><a href="#cb144-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(env, loc, gen)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 464 × 10
   env   loc    year gen   yield height lodging  size protein   oil
   &lt;fct&gt; &lt;fct&gt; &lt;dbl&gt; &lt;fct&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25  8.45    36.7  20.9
 2 L70   Lawes  1970 G02    2.28  1.45     4.25  9.95    37.6  20.7
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 10.8     37.8  21.3
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  10.0     38.4  22.0
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  11       37.5  22.1
 6 L70   Lawes  1970 G06    2.41  1.36     4    11.8     38.2  21.2
 7 L70   Lawes  1970 G07    2.70  1.3      3    11.8     37.4  21.7
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 10       35.2  21.1
 9 L70   Lawes  1970 G09    2.57  1.03     3    11.2     35.9  21.5
10 L70   Lawes  1970 G10    2.98  1.16     3.75 10.8     39.7  20.4
# ℹ 454 more rows</code></pre>
</div>
</div>
<p>To display the levels of a factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb146"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb146-1"><a href="#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(example02<span class="sc">$</span>loc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Brookstead" "Lawes"      "Nambour"    "RedlandBay"</code></pre>
</div>
</div>
<p>To get the number of levels of a factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb148"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb148-1"><a href="#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nlevels</span>(example02<span class="sc">$</span>env)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
</div>
<p><br><br></p>
</section>
</section>
</section>
<section id="pivoting" class="level1">
<h1><span style="color: #2C6D26;"><strong>Pivoting</strong></span></h1>
<p>Data management is an important task during data analysis because most times, datasets do not come in the required shape for analysis and result presentation. Hence, the need for conversion of dataset tables from wide to long format, or vice versa. It is important to understand data frame intuition where variables are in columns, observations are in rows, and values are in the cell.</p>
<p><img src="images/tibble.png" class="img-fluid"></p>
<p>The <code>pivot_wider()</code> or <code>pivot_longer()</code> functions in R <strong>tidyverse</strong> package help reorganize or reshape data values into the needed layout.</p>
<p><img src="images/Pivot.jpg" class="img-fluid"> <br><br></p>
<section id="pivot-longer" class="level2">
<h2 class="anchored" data-anchor-id="pivot-longer"><span style="color:#002D62;"><strong>Pivot Longer</strong></span></h2>
<p>A common problem is a dataset where some of the column names are not names of variables, but values of a variable. The function <code>pivot_longer()</code> transform the dataset in wide format to longer.</p>
<p>Below is the basic R syntax needed to transform data from a wide format to a long format:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb150"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb150-1"><a href="#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_longer</span>(data, cols, <span class="at">names_to =</span> <span class="st">"xxx"</span>, <span class="at">values_to =</span> <span class="st">"yyy"</span>)  <span class="co">#&lt;&lt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>data</code>: a data frame to pivot longer</li>
<li><code>cols</code>: columns to pivot into long format</li>
<li><code>names_to</code>: a character specifying the name of the selected columns to pivot</li>
<li><code>values_to</code>: a character specifying the name of the cell values in the pivoted columns.</li>
</ul>
</section>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example"><span style="color: #002D62;"><strong>Example</strong></span></h2>
<p>To illustrate how this function works, let’s import the Australia Soybean 1970 dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb151"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb151-1"><a href="#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="co"># library(tidyverse)</span></span>
<span id="cb151-2"><a href="#cb151-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"australia.soybean1970.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We have a data frame with 7 variables (env, loc, year, gen, yield, height, and lodging) and 232 observations. The data frame is stored under an object named <strong>dat</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb152"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb152-1"><a href="#cb152-1" aria-hidden="true" tabindex="-1"></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 7
   env   loc    year gen   yield height lodging
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25
 2 L70   Lawes  1970 G02    2.28  1.45     4.25
 3 L70   Lawes  1970 G03    2.57  1.46     3.75
 4 L70   Lawes  1970 G04    2.88  1.26     3.5 
 5 L70   Lawes  1970 G05    2.39  1.34     3.5 
 6 L70   Lawes  1970 G06    2.41  1.36     4   
 7 L70   Lawes  1970 G07    2.70  1.3      3   
 8 L70   Lawes  1970 G08    2.46  0.955    3.25
 9 L70   Lawes  1970 G09    2.57  1.03     3   
10 L70   Lawes  1970 G10    2.98  1.16     3.75
# ℹ 222 more rows</code></pre>
</div>
</div>
<p>As you can see, the dataset is already in wide format as seen from the previous slide. To transform the dataset into a long format, we use the function <code>pivot_longer</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb154"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb154-1"><a href="#cb154-1" aria-hidden="true" tabindex="-1"></a>dat_longer <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span></span>
<span id="cb154-2"><a href="#cb154-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(yield<span class="sc">:</span>lodging, <span class="at">names_to =</span> <span class="st">"trait"</span>, <span class="at">values_to =</span> <span class="st">"values"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb155"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb155-1"><a href="#cb155-1" aria-hidden="true" tabindex="-1"></a>dat_longer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 696 × 6
   env   loc    year gen   trait   values
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;
 1 L70   Lawes  1970 G01   yield     2.39
 2 L70   Lawes  1970 G01   height    1.44
 3 L70   Lawes  1970 G01   lodging   4.25
 4 L70   Lawes  1970 G02   yield     2.28
 5 L70   Lawes  1970 G02   height    1.45
 6 L70   Lawes  1970 G02   lodging   4.25
 7 L70   Lawes  1970 G03   yield     2.57
 8 L70   Lawes  1970 G03   height    1.46
 9 L70   Lawes  1970 G03   lodging   3.75
10 L70   Lawes  1970 G04   yield     2.88
# ℹ 686 more rows</code></pre>
</div>
</div>
<p><br><br></p>
</section>
<section id="pivot-wider" class="level2">
<h2 class="anchored" data-anchor-id="pivot-wider"><span style="color: #2C6D26;"><strong>Pivot Wider</strong></span></h2>
<p>The function <code>pivot_wider()</code> is the opposite of the <code>pivot_longer()</code> function. It transforms the dataset from long format to wider. Below is the basic R syntax needed to transform data from a wide format to a long format:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb157"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb157-1"><a href="#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pivot_wider</span>(data, <span class="at">names_from =</span> <span class="st">"xxx"</span>, <span class="at">values_from =</span> <span class="st">"yyy"</span>)  <span class="co">#&lt;&lt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><code>data</code>: a data frame to pivot wider</li>
<li><code>names_from</code>: the name of the output column</li>
<li><code>values_from</code>: the name of the column to get the cell values from</li>
</ul>
</section>
<section id="example-1" class="level2">
<h2 class="anchored" data-anchor-id="example-1"><span style="color: #002D62;"><strong>Example</strong></span></h2>
<p>To transform the dataset into a wide format, we use the function <code>pivot_wider()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb158"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb158-1"><a href="#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb158-2"><a href="#cb158-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"Longer.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb159"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb159-1"><a href="#cb159-1" aria-hidden="true" tabindex="-1"></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 696 × 6
   env   loc    year gen   trait   values
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;dbl&gt;
 1 L70   Lawes  1970 G01   yield     2.39
 2 L70   Lawes  1970 G01   height    1.44
 3 L70   Lawes  1970 G01   lodging   4.25
 4 L70   Lawes  1970 G02   yield     2.28
 5 L70   Lawes  1970 G02   height    1.45
 6 L70   Lawes  1970 G02   lodging   4.25
 7 L70   Lawes  1970 G03   yield     2.57
 8 L70   Lawes  1970 G03   height    1.46
 9 L70   Lawes  1970 G03   lodging   3.75
10 L70   Lawes  1970 G04   yield     2.88
# ℹ 686 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb161"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb161-1"><a href="#cb161-1" aria-hidden="true" tabindex="-1"></a>dat_wider <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span></span>
<span id="cb161-2"><a href="#cb161-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="st">"trait"</span>, <span class="at">values_from =</span> <span class="st">"values"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb162"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb162-1"><a href="#cb162-1" aria-hidden="true" tabindex="-1"></a>dat_wider</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 7
   env   loc    year gen   yield height lodging
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25
 2 L70   Lawes  1970 G02    2.28  1.45     4.25
 3 L70   Lawes  1970 G03    2.57  1.46     3.75
 4 L70   Lawes  1970 G04    2.88  1.26     3.5 
 5 L70   Lawes  1970 G05    2.39  1.34     3.5 
 6 L70   Lawes  1970 G06    2.41  1.36     4   
 7 L70   Lawes  1970 G07    2.70  1.3      3   
 8 L70   Lawes  1970 G08    2.46  0.955    3.25
 9 L70   Lawes  1970 G09    2.57  1.03     3   
10 L70   Lawes  1970 G10    2.98  1.16     3.75
# ℹ 222 more rows</code></pre>
</div>
</div>
<p><br><br></p>
</section>
</section>
<section id="combining-tables" class="level1">
<h1><span style="color: #2C6D26;"><strong>Combining Tables</strong></span></h1>
<p>So far we have seen how tidy data can be reshaped. However, there are occasions when dataset comes from different data sources and we need to combine them together before we proceed further to analysis or result presentation. The <code>dplyr</code> in R <strong>tidyverse</strong> package offers different mutating join functions to combine datasets together. A mutating join function allows you to combine variables from two tables by matching observations by key variable(s), then copy variables from one table to another.</p>
<p>There are four common mutating joins: <code>left_join</code>, <code>right_join</code>, <code>inner_join</code>, and <code>full_join</code>. They all have the same arguments but return different tables, <em>df1</em> and <em>df2</em> are a pair of data frames to join, and <em>by</em> is a unique character vector variable(s) to join the data frames by.</p>
<section id="left-join" class="level2">
<h2 class="anchored" data-anchor-id="left-join"><span style="color: #002D62;"><strong>Left Join</strong></span></h2>
<p><code>left_join(df1, df2, by)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb164"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb164-1"><a href="#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="co"># join matching values from df2 to df1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/left1.jpg" width="30%"></p>
<p><img src="images/left2.jpg" width="30%"></p>
<p>A left join in R is a kind of database join that joins two data frames together by their columns using a shared key. Only the matching rows from the right data frame are included in the result of a left join, which contains all of the rows from the left data frame. NA values are entered for each column in the corresponding data frame if there is no match.<br>
<br>
<strong>Example</strong> To demonstrate how these mutating joins work, let’s import the pair of data frames needed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb165"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb165-1"><a href="#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb165-2"><a href="#cb165-2" aria-hidden="true" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"df.combine.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"df1"</span>)</span>
<span id="cb165-3"><a href="#cb165-3" aria-hidden="true" tabindex="-1"></a>dat2 <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"df.combine.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"df2"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>dat1</strong> has 15 observations with five variables:gen, yield, height, size, and protein.</p>
<p><strong>dat2</strong> has 15 observations with two variables:gen, oil.</p>
<p>Display the observations in dat1</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb166"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb166-1"><a href="#cb166-1" aria-hidden="true" tabindex="-1"></a>dat1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 5
   gen   yield height  size protein
   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1 G01    2.79  0.97   8.35    39.4
 2 G02    2.62  0.785  9.75    40.6
 3 G03    2.48  0.955 11.4     37.4
 4 G04    2.92  0.76  11.1     36.9
 5 G05    2.14  0.76  11.9     38.7
 6 G06    2.86  0.65  12.2     38.1
 7 G07    2.97  0.8   11.2     37.4
 8 G08    1.65  0.9   11.8     36.6
 9 G09    3.1   0.825 12.2     37.1
10 G10    3.00  0.785 12.0     37.8
11 G11    1.90  0.875  7.4     43.4
12 G12    1.64  1.16   7.45    44.4
13 G13    1.97  1.08   8.25    42.2
14 G14    2.45  0.865  7.65    38.4
15 G15    2.63  0.675  9.05    40.7</code></pre>
</div>
</div>
<p>Display the observations in dat2</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb168"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb168-1"><a href="#cb168-1" aria-hidden="true" tabindex="-1"></a>dat2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 5
   gen   yield height  size   oil
   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 G01    2.39  1.44   8.45  20.9
 2 G02    2.28  1.45   9.95  20.7
 3 G03    2.57  1.46  10.8   21.3
 4 G04    2.88  1.26  10.0   22.0
 5 G05    2.39  1.34  11     22.1
 6 G06    2.41  1.36  11.8   21.2
 7 G07    2.70  1.3   11.8   21.7
 8 G08    2.46  0.955 10     21.1
 9 G09    2.57  1.03  11.2   21.5
10 G10    2.98  1.16  10.8   20.4
11 G16    1.66  1.42   6.95  19.1
12 G17    1.96  1.44   8.35  18.7
13 G18    1.47  1.58   9.3   19.2
14 G19    2.72  1.33   8.25  20.8
15 G20    2.22  1.37   9.3   20.7</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb170"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb170-1"><a href="#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Left join</span></span>
<span id="cb170-2"><a href="#cb170-2" aria-hidden="true" tabindex="-1"></a>df_left <span class="ot">&lt;-</span> <span class="fu">left_join</span>(dat1, dat2)</span>
<span id="cb170-3"><a href="#cb170-3" aria-hidden="true" tabindex="-1"></a>df_left</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 6
   gen   yield height  size protein   oil
   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 G01    2.79  0.97   8.35    39.4    NA
 2 G02    2.62  0.785  9.75    40.6    NA
 3 G03    2.48  0.955 11.4     37.4    NA
 4 G04    2.92  0.76  11.1     36.9    NA
 5 G05    2.14  0.76  11.9     38.7    NA
 6 G06    2.86  0.65  12.2     38.1    NA
 7 G07    2.97  0.8   11.2     37.4    NA
 8 G08    1.65  0.9   11.8     36.6    NA
 9 G09    3.1   0.825 12.2     37.1    NA
10 G10    3.00  0.785 12.0     37.8    NA
11 G11    1.90  0.875  7.4     43.4    NA
12 G12    1.64  1.16   7.45    44.4    NA
13 G13    1.97  1.08   8.25    42.2    NA
14 G14    2.45  0.865  7.65    38.4    NA
15 G15    2.63  0.675  9.05    40.7    NA</code></pre>
</div>
</div>
<ul>
<li><p>The code performs a left join on <code>dat1</code> and <code>dat2</code>, resulting in a new data frame <code>df_left</code> that contains all rows from the left data frame (<code>dat1</code>) along with matching rows from <code>dat2</code>. Rows in <code>dat1</code> without a corresponding match in <code>dat2</code> will have <code>NA</code> in their resulting columns for data from <code>dat2</code>.</p>
<p><br><br></p></li>
</ul>
</section>
<section id="right-join" class="level2">
<h2 class="anchored" data-anchor-id="right-join"><span style="color: #002D62;"><strong>Right Join</strong></span></h2>
<p><code>right_join(df1, df2, by)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb172"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb172-1"><a href="#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="co"># join matching values from df2 to df1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/right1.jpg" width="30%"></p>
<p><img src="images/right2.jpg" width="30%"></p>
<p>A right join is a type of database join that combines two data frames based on a common key, similar to a left join but with a focus on retaining all the rows from the right data frame. When performing a right join, all rows from the right data frame are included in the result, and only the matching rows from the left data frame are included. If there is no match, the corresponding columns of the left data frame will be filled with&nbsp;<code>NA</code>&nbsp;values</p>
<p><strong>Example</strong></p>
<p>Continuing with the previous data,</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb173"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb173-1"><a href="#cb173-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Right join</span></span>
<span id="cb173-2"><a href="#cb173-2" aria-hidden="true" tabindex="-1"></a>df_right <span class="ot">&lt;-</span> <span class="fu">right_join</span>(dat1, dat2)</span>
<span id="cb173-3"><a href="#cb173-3" aria-hidden="true" tabindex="-1"></a>df_right</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 6
   gen   yield height  size protein   oil
   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 G01    2.39  1.44   8.45      NA  20.9
 2 G02    2.28  1.45   9.95      NA  20.7
 3 G03    2.57  1.46  10.8       NA  21.3
 4 G04    2.88  1.26  10.0       NA  22.0
 5 G05    2.39  1.34  11         NA  22.1
 6 G06    2.41  1.36  11.8       NA  21.2
 7 G07    2.70  1.3   11.8       NA  21.7
 8 G08    2.46  0.955 10         NA  21.1
 9 G09    2.57  1.03  11.2       NA  21.5
10 G10    2.98  1.16  10.8       NA  20.4
11 G16    1.66  1.42   6.95      NA  19.1
12 G17    1.96  1.44   8.35      NA  18.7
13 G18    1.47  1.58   9.3       NA  19.2
14 G19    2.72  1.33   8.25      NA  20.8
15 G20    2.22  1.37   9.3       NA  20.7</code></pre>
</div>
</div>
<p>The right join operation retains all rows from the right data frame (<code>dat2</code>) and only those rows from the left data frame (<code>dat1</code>) that match based on the specified keys. If there are entries in&nbsp;<code>dat2</code>&nbsp;without corresponding matches in&nbsp;<code>dat1</code>, the output will show&nbsp;<code>NA</code>&nbsp;in place of those unmatched entries from&nbsp;<code>dat1</code></p>
<p><br><br></p>
</section>
<section id="inner-join" class="level2">
<h2 class="anchored" data-anchor-id="inner-join"><span style="color: #002D62;"><strong>Inner Join</strong></span></h2>
<p><code>inner_join(df1, df2, by)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb175"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb175-1"><a href="#cb175-1" aria-hidden="true" tabindex="-1"></a><span class="co"># join values from df2 to df1 and retain only matching rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/inner1.jpg" width="30%"></p>
<p><img src="images/inner2.jpg" width="30%"></p>
<p>An inner join is a type of database join that combines two data frames (or tables) based on a common key or keys, returning only those rows where there is a match in both data frames. In other words, an inner join retrieves the intersection of the two dataset</p>
<p><strong>Example</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb176"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb176-1"><a href="#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Inner join</span></span>
<span id="cb176-2"><a href="#cb176-2" aria-hidden="true" tabindex="-1"></a>df_inner <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(dat1, dat2)</span>
<span id="cb176-3"><a href="#cb176-3" aria-hidden="true" tabindex="-1"></a>df_inner</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 0 × 6
# ℹ 6 variables: gen &lt;chr&gt;, yield &lt;dbl&gt;, height &lt;dbl&gt;, size &lt;dbl&gt;,
#   protein &lt;dbl&gt;, oil &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The resulting data frame (<code>df_inner</code>) contains only those rows where there are matching values in the&nbsp;<code>id</code>&nbsp;column of both&nbsp;<code>dat1</code>&nbsp;and&nbsp;<code>dat2</code></p>
<p><br><br></p>
</section>
<section id="full-join" class="level2">
<h2 class="anchored" data-anchor-id="full-join"><span style="color: #002D62;"><strong>Full join</strong></span></h2>
<p><code>full_join(df1, df2, by)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb178"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb178-1"><a href="#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="co"># join values from df2 to df1 and retain all rows, all values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><img src="images/full1.jpg" width="30%"></p>
<p><img src="images/full2.jpg" width="30%"></p>
<p>A full join (or full outer join) is a type of database join that combines the results of both left and right joins. This means that a full join returns all the rows from both data frames (or tables), regardless of whether there is a match between them. If a row in one data frame does not have a corresponding match in the other, the result will contain&nbsp;<code>NA</code>&nbsp;(or missing values) for the columns of the unmatched row from the other data frame.</p>
<p><strong>Example</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb179"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb179-1"><a href="#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Full join</span></span>
<span id="cb179-2"><a href="#cb179-2" aria-hidden="true" tabindex="-1"></a>df_full <span class="ot">&lt;-</span> <span class="fu">full_join</span>(dat1, dat2)</span>
<span id="cb179-3"><a href="#cb179-3" aria-hidden="true" tabindex="-1"></a>df_full</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 30 × 6
   gen   yield height  size protein   oil
   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
 1 G01    2.79  0.97   8.35    39.4    NA
 2 G02    2.62  0.785  9.75    40.6    NA
 3 G03    2.48  0.955 11.4     37.4    NA
 4 G04    2.92  0.76  11.1     36.9    NA
 5 G05    2.14  0.76  11.9     38.7    NA
 6 G06    2.86  0.65  12.2     38.1    NA
 7 G07    2.97  0.8   11.2     37.4    NA
 8 G08    1.65  0.9   11.8     36.6    NA
 9 G09    3.1   0.825 12.2     37.1    NA
10 G10    3.00  0.785 12.0     37.8    NA
# ℹ 20 more rows</code></pre>
</div>
</div>
<p>The code&nbsp;<code>df_full &lt;- full_join(dat1, dat2)</code>&nbsp;effectively creates a new data frame that combines data from&nbsp;<code>dat1</code>&nbsp;and&nbsp;<code>dat2</code>, ensuring that all records are retained, either matched or unmatched. This type of join is particularly useful in exploratory data analysis and situations where preserving all relevant data is critical for further analysis and interpretation.</p>
<p><br><br></p>
</section>
</section>
<section id="creating-groups" class="level1">
<h1><span style="color: #2C6D26;"><strong>Creating Groups</strong></span></h1>
<p>Data wrangling in R sometimes requires modification or creating a new variable based on certain possible conditions during data analysis.</p>
<p>It is possible to create new variables with the mutate() function in the tidyverse package.</p>
<p>The <code>case_when()</code> function allows you to vectorize multiple <code>if_else</code> statements, i.e.&nbsp;you test condition-1, and then output output-value-1 if the condition-1 is true, then test condition-2, and output output-value-2 if condition-2 is true, the logical statements continue until you specify a value to output if none of the conditions were true.</p>
<p>However, if we are interested in creating a new variable within a dataframe based on certain conditions with some <code>if-elif-else</code> style logic, then the case_when() function is used with the <code>mutate()</code> function, both are in the <strong>tidyverse</strong> package.</p>
<p>To illustrate the description in the previous slide, let’s consider the image below</p>
<p><img src="images/case_when.jpg" class="img-fluid"></p>
<p>The <code>TRUE~</code> is equivalent to the <code>‘else’</code> in the <code>‘if-else’</code> statement.</p>
<p>It is important to note that the conditions are evaluated in order, therefore one must proceed from the most specific to the most general condition.</p>
<p>Let’s demonstrate how <code>case_when</code> works with these examples using the Australia Soybean 1970 dataset.</p>
<p>We are going to create four lodging categories such as &gt;=1 = ‘No Lodging’, &gt;=1.5 = ‘Mild Lodging’, &gt;=2.5 = ‘Moderate Lodging’, and &gt;=3.5 = ‘Heavy Lodging’.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb181"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb181-1"><a href="#cb181-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"australia.soybean1970.csv"</span>)</span>
<span id="cb181-2"><a href="#cb181-2" aria-hidden="true" tabindex="-1"></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 7
   env   loc    year gen   yield height lodging
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
 1 L70   Lawes  1970 G01    2.39  1.44     4.25
 2 L70   Lawes  1970 G02    2.28  1.45     4.25
 3 L70   Lawes  1970 G03    2.57  1.46     3.75
 4 L70   Lawes  1970 G04    2.88  1.26     3.5 
 5 L70   Lawes  1970 G05    2.39  1.34     3.5 
 6 L70   Lawes  1970 G06    2.41  1.36     4   
 7 L70   Lawes  1970 G07    2.70  1.3      3   
 8 L70   Lawes  1970 G08    2.46  0.955    3.25
 9 L70   Lawes  1970 G09    2.57  1.03     3   
10 L70   Lawes  1970 G10    2.98  1.16     3.75
# ℹ 222 more rows</code></pre>
</div>
</div>
<p><br><br></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb183"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb183-1"><a href="#cb183-1" aria-hidden="true" tabindex="-1"></a>dat_new <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span></span>
<span id="cb183-2"><a href="#cb183-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(</span>
<span id="cb183-3"><a href="#cb183-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">lodging_grp =</span> <span class="fu">case_when</span>(</span>
<span id="cb183-4"><a href="#cb183-4" aria-hidden="true" tabindex="-1"></a>                                      lodging <span class="sc">&gt;=</span> <span class="fl">3.5</span> <span class="sc">~</span> <span class="st">"Heavy Lodging"</span>,</span>
<span id="cb183-5"><a href="#cb183-5" aria-hidden="true" tabindex="-1"></a>                                          lodging <span class="sc">&gt;=</span> <span class="fl">2.5</span> <span class="sc">~</span> <span class="st">"Moderate Lodging"</span>,</span>
<span id="cb183-6"><a href="#cb183-6" aria-hidden="true" tabindex="-1"></a>                                        lodging <span class="sc">&gt;=</span> <span class="fl">1.5</span> <span class="sc">~</span> <span class="st">"Mild Lodging"</span>,</span>
<span id="cb183-7"><a href="#cb183-7" aria-hidden="true" tabindex="-1"></a>                                          lodging <span class="sc">&gt;=</span> <span class="dv">1</span> <span class="sc">~</span> <span class="st">"No Lodging"</span>,</span>
<span id="cb183-8"><a href="#cb183-8" aria-hidden="true" tabindex="-1"></a>                                                       <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"NA"</span>)</span>
<span id="cb183-9"><a href="#cb183-9" aria-hidden="true" tabindex="-1"></a>             )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb184"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb184-1"><a href="#cb184-1" aria-hidden="true" tabindex="-1"></a>dat_new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 8
   env   loc    year gen   yield height lodging lodging_grp     
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;           
 1 L70   Lawes  1970 G01    2.39  1.44     4.25 Heavy Lodging   
 2 L70   Lawes  1970 G02    2.28  1.45     4.25 Heavy Lodging   
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 Heavy Lodging   
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  Heavy Lodging   
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  Heavy Lodging   
 6 L70   Lawes  1970 G06    2.41  1.36     4    Heavy Lodging   
 7 L70   Lawes  1970 G07    2.70  1.3      3    Moderate Lodging
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 Moderate Lodging
 9 L70   Lawes  1970 G09    2.57  1.03     3    Moderate Lodging
10 L70   Lawes  1970 G10    2.98  1.16     3.75 Heavy Lodging   
# ℹ 222 more rows</code></pre>
</div>
</div>
<p>Also, we may be interested in creating a new variable from the existing categorical variable.</p>
<p>Let’s use the new data set <code>dat_new</code> to demonstrate this process using <code>mutate</code> and <code>case_when</code> functions and introduce the <code>IN</code> operator <code>%in%</code> i.e.&nbsp;We create two lodging categories such that <code>'No Lodging'</code> and <code>'Mild Lodging'</code> will be <code>"No Lodging"</code>, and <code>'Moderate Lodging'</code> and <code>'Heavy Lodging'</code> will be <code>"Lodging"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb186"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb186-1"><a href="#cb186-1" aria-hidden="true" tabindex="-1"></a>dat_new <span class="ot">&lt;-</span> dat_new <span class="sc">|&gt;</span></span>
<span id="cb186-2"><a href="#cb186-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">mutate</span>(</span>
<span id="cb186-3"><a href="#cb186-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">lodging_grp2 =</span> <span class="fu">case_when</span>(</span>
<span id="cb186-4"><a href="#cb186-4" aria-hidden="true" tabindex="-1"></a>          lodging_grp <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Heavy Lodging"</span>,<span class="st">"Moderate Lodging"</span>)  <span class="sc">~</span> <span class="st">"Lodging"</span>,</span>
<span id="cb186-5"><a href="#cb186-5" aria-hidden="true" tabindex="-1"></a>          lodging_grp <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"No Lodging"</span>, <span class="st">"Mild Lodging"</span>) <span class="sc">~</span> <span class="st">"No Lodging"</span>,</span>
<span id="cb186-6"><a href="#cb186-6" aria-hidden="true" tabindex="-1"></a>                                                    <span class="cn">TRUE</span>   <span class="sc">~</span> <span class="st">"NA"</span>)</span>
<span id="cb186-7"><a href="#cb186-7" aria-hidden="true" tabindex="-1"></a>        )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb187"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb187-1"><a href="#cb187-1" aria-hidden="true" tabindex="-1"></a>dat_new</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 232 × 9
   env   loc    year gen   yield height lodging lodging_grp      lodging_grp2
   &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;       
 1 L70   Lawes  1970 G01    2.39  1.44     4.25 Heavy Lodging    Lodging     
 2 L70   Lawes  1970 G02    2.28  1.45     4.25 Heavy Lodging    Lodging     
 3 L70   Lawes  1970 G03    2.57  1.46     3.75 Heavy Lodging    Lodging     
 4 L70   Lawes  1970 G04    2.88  1.26     3.5  Heavy Lodging    Lodging     
 5 L70   Lawes  1970 G05    2.39  1.34     3.5  Heavy Lodging    Lodging     
 6 L70   Lawes  1970 G06    2.41  1.36     4    Heavy Lodging    Lodging     
 7 L70   Lawes  1970 G07    2.70  1.3      3    Moderate Lodging Lodging     
 8 L70   Lawes  1970 G08    2.46  0.955    3.25 Moderate Lodging Lodging     
 9 L70   Lawes  1970 G09    2.57  1.03     3    Moderate Lodging Lodging     
10 L70   Lawes  1970 G10    2.98  1.16     3.75 Heavy Lodging    Lodging     
# ℹ 222 more rows</code></pre>
</div>
</div>
<p><br><br></p>
</section>
<section id="strings" class="level1">
<h1><span style="color: #2C6D26;"><strong>Strings</strong></span></h1>
<p>As we all know that data comes in different formats, numeric or non-numeric (text/string) data format. Data wrangling of non-numeric data sometimes requires splitting of the cell into multiple individual cells or combining multiple cells into a single cell before analysis.</p>
<p>There are some functions in the tidyverse package used for this purpose such as <code>unite()</code>, <code>separate()</code>, and <code>str_sub()</code>.</p>
<ul>
<li><p><code>unite()</code>: collapse cells across several columns into a single column.</p></li>
<li><p><code>separate()</code>: separate each cell in a column into several columns.</p></li>
<li><p><code>str_sub()</code>: extract a substring from a character vector.</p></li>
</ul>
<p>Let’s use a fictitious data set called <strong>BadData</strong> to demonstrate how these functions work.</p>
<p>The data set has seven (7) variables: Gen: A combination of location, genotype, and replication, Year: Year of trials, Traits: Measured traits (Trait1 – Trait5)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb189"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb189-1"><a href="#cb189-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"BadData.csv"</span>)</span>
<span id="cb189-2"><a href="#cb189-2" aria-hidden="true" tabindex="-1"></a>dat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 360 × 7
   Gen       Year Trait1 Trait2 Trait3 Trait4 Trait5
   &lt;chr&gt;    &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 IBG10-1   2020     12     12     58     63     85
 2 IBG10-2   2020      9      9     62     67     96
 3 IBG10-3   2020     12     12     56     63     96
 4 IBG11-1   2020     10     10     56     60     95
 5 IBG11-2   2020      9      9     56     60    102
 6 IBG11-3   2020     10     10     57     60     97
 7 IBG12-1   2020     10     10     50     59     84
 8 IBG12-2   2020     11     11     53     56     84
 9 IBG12-3   2020     12     12     57     60     92
10 IBG126-1  2020     11     10     51     58     84
# ℹ 350 more rows</code></pre>
</div>
</div>
<p>The first task will be to create separate variables for location, genotype, and replication from the Gen variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb191"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb191-1"><a href="#cb191-1" aria-hidden="true" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> dat <span class="sc">|&gt;</span> </span>
<span id="cb191-2"><a href="#cb191-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(Gen, <span class="at">sep =</span> <span class="st">"-"</span>, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"LocGen"</span>, <span class="st">"Rep"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb191-3"><a href="#cb191-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb191-4"><a href="#cb191-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">Location =</span> <span class="fu">str_sub</span>(LocGen, <span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb191-5"><a href="#cb191-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">Gen =</span> <span class="fu">str_sub</span>(LocGen, <span class="dv">3</span>, <span class="dv">5</span>)</span>
<span id="cb191-6"><a href="#cb191-6" aria-hidden="true" tabindex="-1"></a>     ) <span class="sc">|&gt;</span> </span>
<span id="cb191-7"><a href="#cb191-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Location, Gen, Rep, Year, Trait1, Trait2, Trait3, Trait4, Trait5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb192"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb192-1"><a href="#cb192-1" aria-hidden="true" tabindex="-1"></a>dat1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 360 × 9
   Location Gen   Rep    Year Trait1 Trait2 Trait3 Trait4 Trait5
   &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 IB       G10   1      2020     12     12     58     63     85
 2 IB       G10   2      2020      9      9     62     67     96
 3 IB       G10   3      2020     12     12     56     63     96
 4 IB       G11   1      2020     10     10     56     60     95
 5 IB       G11   2      2020      9      9     56     60    102
 6 IB       G11   3      2020     10     10     57     60     97
 7 IB       G12   1      2020     10     10     50     59     84
 8 IB       G12   2      2020     11     11     53     56     84
 9 IB       G12   3      2020     12     12     57     60     92
10 IB       G12   1      2020     11     10     51     58     84
# ℹ 350 more rows</code></pre>
</div>
</div>
<p>Also, we may be interested in creating a new variable which will be a combination of at least two variables. Suppose we want to create a variable called environment <code>(Env)</code> using the data set above by combining the Location and Year together.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb194"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb194-1"><a href="#cb194-1" aria-hidden="true" tabindex="-1"></a>dat1 <span class="ot">&lt;-</span> dat1 <span class="sc">|&gt;</span></span>
<span id="cb194-2"><a href="#cb194-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">unite</span>(Location, Year, <span class="at">col =</span> <span class="st">"Env"</span>, <span class="at">sep =</span> <span class="st">"-"</span>)</span>
<span id="cb194-3"><a href="#cb194-3" aria-hidden="true" tabindex="-1"></a>dat1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 360 × 8
   Env     Gen   Rep   Trait1 Trait2 Trait3 Trait4 Trait5
   &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
 1 IB-2020 G10   1         12     12     58     63     85
 2 IB-2020 G10   2          9      9     62     67     96
 3 IB-2020 G10   3         12     12     56     63     96
 4 IB-2020 G11   1         10     10     56     60     95
 5 IB-2020 G11   2          9      9     56     60    102
 6 IB-2020 G11   3         10     10     57     60     97
 7 IB-2020 G12   1         10     10     50     59     84
 8 IB-2020 G12   2         11     11     53     56     84
 9 IB-2020 G12   3         12     12     57     60     92
10 IB-2020 G12   1         11     10     51     58     84
# ℹ 350 more rows</code></pre>
</div>
</div>
<section id="exercise" class="level2">
<h2 class="anchored" data-anchor-id="exercise"><span style="color: #2C6D26;"><strong>Exercise</strong></span></h2>
<ol type="1">
<li><p>Import Example-02.csv to R and save it to an object named example02 Display the example02 object filter the data by considering: locations Nambour and RedlandBay genotypes G01, G57, and G58, location Brookstead for the year 1970 location Lawes yield between 2 and 3 inclusive, oil greater than 22</p></li>
<li><p>Import <strong>Example-02.csv</strong> to R and save to an object named <strong>example02</strong> Create a new variable called <code>ENV</code> by combining the first three letters in <code>loc</code> and the last two digit in <code>year</code>. Categorize the <code>yield</code> values of at least 3 as <code>"High"</code> and other values as <code>"Low"</code> into a new variable called <code>yield_grp</code>. Select <code>ENV</code>, <code>gen</code>, <code>yield</code>, <code>yield_grp</code>, <code>height</code>, and <code>oil</code> and transform the dataset using appropriate variables as <code>traits</code>.</p></li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>