<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title> Logistic Regression </title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Logistic Regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="Logistic Regression_files/libs/quarto-html/quarto.js"></script>
<script src="Logistic Regression_files/libs/quarto-html/popper.min.js"></script>
<script src="Logistic Regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Logistic Regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="Logistic Regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Logistic Regression_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Logistic Regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Logistic Regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Logistic Regression_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="-1">
    <h2 id="toc-title">Outline</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span style="color: #234F1E;"><strong>Introduction</strong></span></a></li>
  <li><a href="#advantages-of-logistic-regression" id="toc-advantages-of-logistic-regression" class="nav-link" data-scroll-target="#advantages-of-logistic-regression"><span style="color: #234F1E;"><strong>Advantages of Logistic Regression</strong></span></a></li>
  <li><a href="#the-logistic-curve" id="toc-the-logistic-curve" class="nav-link" data-scroll-target="#the-logistic-curve"><span style="color: #234F1E;"><strong>The Logistic Curve</strong></span></a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span style="color: #234F1E;"><strong>Assumptions</strong></span></a></li>
  <li><a href="#comparison-between-linear-regression-and-logistic-regression" id="toc-comparison-between-linear-regression-and-logistic-regression" class="nav-link" data-scroll-target="#comparison-between-linear-regression-and-logistic-regression"><span style="color: #234F1E;"><strong>Comparison Between Linear Regression and Logistic Regression</strong></span></a></li>
  <li><a href="#models-of-logistic-regression" id="toc-models-of-logistic-regression" class="nav-link" data-scroll-target="#models-of-logistic-regression"><span style="color: #234F1E;"><strong>Models of Logistic Regression</strong></span></a></li>
  <li><a href="#binary-logistic-regression" id="toc-binary-logistic-regression" class="nav-link" data-scroll-target="#binary-logistic-regression"><span style="color: #234F1E;"><strong>Binary Logistic Regression</strong></span></a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span style="color: #002D62;">Example</span></a></li>
  </ul></li>
  <li><a href="#multinomial-logistic-regression" id="toc-multinomial-logistic-regression" class="nav-link" data-scroll-target="#multinomial-logistic-regression"><span style="color: #234F1E;"><strong>Multinomial Logistic Regression</strong></span></a>
  <ul class="collapse">
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"><span style="color: #002D62;">Example</span></a></li>
  </ul></li>
  <li><a href="#ordinal-logistic-regression" id="toc-ordinal-logistic-regression" class="nav-link" data-scroll-target="#ordinal-logistic-regression"><span style="color: #234F1E;"><strong>Ordinal Logistic Regression</strong></span></a>
  <ul class="collapse">
  <li><a href="#example-2" id="toc-example-2" class="nav-link" data-scroll-target="#example-2"><span style="color: #002D62;">Example</span></a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><p style="color:black,text-align:center"><br>
Logistic Regression<br>
</p></h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author"><font color="#ff6600"><b>Biometrics Unit</b></font> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <font color="#ff6600"><b>International Institute of Tropical Agriculture (IITA)</b></font>
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1><span style="color: #234F1E;"><strong>Introduction</strong></span></h1>
<p>Logistic regression, also known as the logistic model or logit model, examines how multiple independent variables relate to a categorical dependent variable. It predicts the probability of an event happening by modeling data to fit a logistic curve.</p>
<p>Logistic regression is a supervised machine learning algorithm that accomplishes binary classification tasks by predicting the probability of an outcome, event, or observation. The model delivers a binary or dichotomous outcome limited to two possible outcomes: yes/no, 0/1, or true/false.</p>
<p>Logistic regression is a type of statistical model that is used to predict the probability of a certain event happening. It may be used to determine if an email is spam or not, as well as diagnose illnesses by determining whether certain symptoms are present or absent based on test results from patients. It works by taking input variables and transforming them into a probability value between 0 and 1, where 0 represents a low probability and 1 represents a high probability.</p>
<p>For example, a researcher wants to measure the poverty status of farmers in a certain locality using their annual income and decided to classify them as poor (1) and not poor (0) based on a certain threshold. Then logistic regression could be used to determine the factors influencing poverty among the farmers using predictor variables like gender, age, farm size, household size, years of farming experience, etc.</p>
<p>The reason it is named “logistic” is that an S-shaped curve (sigmoid function) is produced when the input variables are transformed using a mathematical function known as the logistic function.</p>
</section>
<section id="advantages-of-logistic-regression" class="level1">
<h1><span style="color: #234F1E;"><strong>Advantages of Logistic Regression</strong></span></h1>
<p>The logistic regression analysis has several advantages in machine learning. These are highlighted below.</p>
<p><img src="images/advanlog.png" alt="Advantages of Logistic Regression" style="width:50%;"></p>
<p><a href="https://www.spiceworks.com/tech/artificial-intelligence/articles/what-is-logistic-regression/">Source</a></p>
<ol type="1">
<li><p>It is easier to implement machine learning models: Logistic regression is computationally efficient compared to many other machine learning methods, making it easier to implement, interpret, and train.</p></li>
<li><p>Optimal for linearly separable data: Logistic regression is specifically designed for binary classification tasks, effectively categorizing data into two distinct groups when the data is linearly separable.</p></li>
<li><p>Provides valuable insights: Logistic regression coefficients indicate both the strength and direction of the relationship between predictor variables and the outcome.</p></li>
</ol>
</section>
<section id="the-logistic-curve" class="level1">
<h1><span style="color: #234F1E;"><strong>The Logistic Curve</strong></span></h1>
<p>Logistic regression is a technique used to model the relationship between a binary (dichotomous) response variable ( y ) and a numerical predictor variable ( x ). It fits a logistic curve, which is an S-shaped or sigmoid curve, to represent how ( y ) changes as ( x ) varies. This method is particularly useful when ( y ) represents binary outcomes coded as 0 (failure) or 1 (success), such as in cases of modeling population growth or other similar scenarios.</p>
<p>Logistic regression fits α and β, the regression coefficients. The logistic or logit function is used to transform an ‘S’-shaped curve into an approximately straight line and to change the range of the proportion from [0 – 1] to [(-∞) - (+∞)]</p>
<p><img src="images/logcurve.png" alt="Logistic Curve" style="width:50%;"></p>
<p><a href="https://images.spiceworks.com/wp-content/uploads/2022/04/11040521/46-4-e1715636469361.png">Source</a></p>
<p><b></b></p><b>
<p style="text-align: center; color: black;">
</p><p>logit(y)= ln (odds)= ln (<span class="math inline">\(\frac{P}{1 - P}\)</span> ) = <span class="math inline">\(\alpha\)</span> + <span class="math inline">\(\beta\)</span>X</p>
<p></p>
</b><p><b></b></p>
</section>
<section id="assumptions" class="level1">
<h1><span style="color: #234F1E;"><strong>Assumptions</strong></span></h1>
<ul>
<li><p><strong>B</strong>inary Outcome: The dependent variable should be binary in nature, i.e.&nbsp;it should take on one of two possible vales coded as 0 and 1, “success” and “failure”, “yes” and “no”.</p></li>
<li><p><strong>I</strong>ndependence of Errors: This implies that the error for each observation in the dataset should not be related to the error for any other observation. If violations of independence are detected, this may indicate the need to consider a different model or to account for correlation or clustering in the data using other methods such as mixed effects model.</p></li>
<li><p><strong>L</strong>inearity of the Logit: This means that the relationship between the independent variables and the log-odds of the outcome is linear. This means that the effect of the independent variables on the log-odds of the outcome is constant across the range of the independent variables. Logistic regression can accommodate non-linear relationships between the independent and dependent variables by employing a non-linear log transformation of the linear regression framework.</p></li>
<li><p><strong>Large Sample Size</strong>: A relatively large sample size is required to detect meaningful effects and to ensure stability of estimates in Logistic regression. A small sample size can lead to overfitting, where the model captures noise rather than the underlying signal in the data, and underpowered statistical tests, which may fail to detect significant effects due to inadequate sample size.</p></li>
<li><p><strong>Outliers</strong>: The dataset is assumed to be free of extreme outliers and significant observations for the purposes of logistic regression. To deal with outliers, you can do any of the following:</p>
<ol type="1">
<li>Replace the outliers with a mean or median value</li>
<li>Eliminate the outliers</li>
<li>Keep the outliers and maintain a record while reporting the regression results.</li>
</ol></li>
<li><p><strong>No Multicollinearity</strong>: The assumption of no or low multicollinearity among independent variables is quite vital in logistic regression. When two or more explanatory variables have a high degree of correlation with one another, the regression model cannot obtain unique or independent information from them. This phenomenon is known as multicollinearity. A high enough degree of correlation between variables may make it difficult to fit and comprehend the model.</p></li>
</ul>
<p>The acronym <strong>BILLION</strong> gives a useful way to remember the six conditions that makes up the Logistic Regression Model.</p>
<p><img src="images/assumlog.png" width="50%"></p>
<p><a href="https://images.spiceworks.com/wp-content/uploads/2022/04/11041034/50-e1715636496628.png">Source</a></p>
</section>
<section id="comparison-between-linear-regression-and-logistic-regression" class="level1">
<h1><span style="color: #234F1E;"><strong>Comparison Between Linear Regression and Logistic Regression</strong></span></h1>
<p>The following are the comparison that exist between linear and logistic regression</p>
<p><img src="images/loglin.png"></p>
<p>Linear regression is not suitable for binary dependent variables due to several reasons. Firstly, the distribution of the binary variable ( Y ) is not normal; it follows a Bernoulli distribution rather than a Gaussian distribution assumed by linear regression. Secondly, using linear regression may lead to incomparable results because the scale and interpretation of the left-hand side (the binary outcome) and the right-hand side (predictors) of the model are fundamentally different when applied to a binary outcome.</p>
<p>The difference between logistic regression model and a linear regression model is that the outcome variable in logistic regression is binary and dichotomous.</p>
</section>
<section id="models-of-logistic-regression" class="level1">
<h1><span style="color: #234F1E;"><strong>Models of Logistic Regression</strong></span></h1>
<p>There are basically 3 types of logistic regression model, these are:</p>
<ol type="1">
<li>Binary Logistic Regression</li>
<li>Multinomial Logistic Regression</li>
<li>Ordinal Logistic Regression</li>
</ol>
</section>
<section id="binary-logistic-regression" class="level1">
<h1><span style="color: #234F1E;"><strong>Binary Logistic Regression</strong></span></h1>
<p>Binary logistic regression belongs to the broader category of statistical models known as generalized linear models. What sets binary logistic regression apart from other models within this category is its specific application to dependent variables that have two distinct levels.</p>
<p>As seen above, binary logistic regression is suitable when the dependent variable has two categories, and the independent variables are either continuous or categorical. Binary logistic regression is used when we are trying to predict a dependent variable with only two outcomes (dichotomous variable), for example, yes and No.</p>
<p>Logistic regression has the coefficients of parameters like the linear regression and in the addition has the odd ratio which is the exponential of the coefficient.</p>
<p>Odd ratio is <span class="math inline">\(\varepsilon^{\beta}\)</span></p>
<p>The equation for binary logistic regression expression is as shown below:</p>
<p><span class="math inline">\(log\frac{p}{1 - p}\)</span> = Y= <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1X_1\)</span> + <span class="math inline">\(\beta_2X_2\)</span> + … + <span class="math inline">\(\beta_kX_k\)</span></p>
<p>Where <span class="math inline">\(log\frac{p}{1 - p}\)</span> is the odd ratio (Dependent variables)</p>
<p><span class="math inline">\(\beta_0\)</span> = Constant or intercept term in the equation.</p>
<p><span class="math inline">\(\beta_1\)</span>,…<span class="math inline">\(\beta_k\)</span> are the logistic regression coefficients (Coefficient of variable )</p>
<p><span class="math inline">\(X_1\)</span>…<span class="math inline">\(X_k\)</span> = Independent variables</p>
<p><span class="math inline">\(\varepsilon\)</span> = Error Term</p>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example"><span style="color: #002D62;">Example</span></h2>
<p>A sugar cane farmer wants to visually select seedlings to plant in another location. The decision is to select (1) or reject a seedling based on the number of stalks, height (m), stalk diameter, and seedling cane yield (kg). In this case, four of the explanatory variables are quantitative, one is qualitative and the response variable is dichotomous, therefore the logistic regression can the used for the analysis.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read in data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"Sugar cane.xlsx"</span>, <span class="at">sheet =</span> <span class="st">"Sugar cane"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat) <span class="co"># print the first six rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  Choice Stalks Height Diameter  Cane Variety
   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
1      1     23   2.37     1.7  12.4        2
2      0     11   2.25     1.68  5.49       3
3      0      9   2.5      1.93  6.59       2
4      1     25   2.4      2.12 21.2        2
5      1     20   2.5      1.7  11.4        1
6      0     12   1.9      1.51  4.08       1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(Choice,Variety), factor)) <span class="co">#convert </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><br><br></p>
<p><strong>The Logistic Model</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>model_log <span class="ot">&lt;-</span> <span class="fu">glm</span>(Choice <span class="sc">~</span> Cane <span class="sc">+</span> Diameter <span class="sc">+</span> Height, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> dat, <span class="at">family =</span> binomial)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Choice ~ Cane + Diameter + Height, family = binomial, 
    data = dat)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)  
(Intercept)  -5.2139    15.5265  -0.336   0.7370  
Cane          2.3901     1.1340   2.108   0.0351 *
Diameter     -6.8924     4.9139  -1.403   0.1607  
Height        0.8381     6.6179   0.127   0.8992  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 40.381  on 29  degrees of freedom
Residual deviance: 11.797  on 26  degrees of freedom
AIC: 19.797

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p><strong>Formula:</strong> The model predicts Choice (a binary outcome) based on three predictors: Cane, Diameter, and Height.</p>
<p><strong>Family:</strong> The model uses a binomial distribution, suitable for binary response variables. <strong>Coefficients Intercept:</strong> The estimated intercept is -5.2139. This represents the log-odds of the outcome (Choice = 1) when all predictors are at their reference level (or zero). However, the high standard error (15.5265) indicates that this estimate is not statistically significant (p-value = 0.7370), meaning it is not reliable.</p>
<p><strong>Cane:</strong> The coefficient for Cane is 2.3901, with a p-value of 0.0351, which is statistically significant (denoted by *). This suggests that for each one-unit increase in Cane, the log-odds of choosing the outcome (Choice = 1) increases by approximately 2.39. In practical terms, this implies that Cane has a positive influence on the likelihood of the event happening.</p>
<p><strong>Diameter:</strong> The coefficient for Diameter is -6.8924, with a p-value of 0.1607, indicating it is not statistically significant. A negative coefficient suggests that as Diameter increases, the log-odds of the outcome decrease, but we cannot conclude that this effect is meaningful due to the p-value being above the common threshold of 0.05.</p>
<p><strong>Height:</strong> The coefficient for Height is 0.8381, but like Diameter, it has a very high p-value (0.8992), implying it is not statistically significant. Therefore, Height does not appear to have a meaningful impact on the outcome.</p>
<p><strong>Model Fit Information</strong></p>
<p><strong>Null Deviance:</strong> 40.381, which measures the difference in the likelihood of the model with only an intercept compared to the saturated model.</p>
<p><strong>Residual Deviance:</strong> 11.797, which is considerably lower than the null deviance, suggesting that the predictors explain a significant amount of variance in the response variable. The degrees of freedom for residuals (26) suggests there are enough observations after accounting for the parameters estimated.</p>
<p><strong>AIC (Akaike Information Criterion):</strong> 19.797, a measure used for model comparison, lower values indicate a better fit when comparing multiple models.</p>
<p>Among the predictors, only cane seems to have a statistically significant impact on the likelihood of the choice of seedling selected or not selected. In contrast, Diameter and Height do not appear to significantly affect the choice of seedling selected or not selected. The model does fit the data better than a null model, as indicated by the reduction in deviance, but the overall significance and impact of some predictors are weak.</p>
<section id="variable-importance" class="level3">
<h3 class="anchored" data-anchor-id="variable-importance">Variable Importance</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>caret<span class="sc">::</span><span class="fu">varImp</span>(model_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           Overall
Cane     2.1076503
Diameter 1.4026300
Height   0.1266381</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(model_log))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> (Intercept)         Cane     Diameter       Height 
 0.005440294 10.914966068  0.001015469  2.311918797 </code></pre>
</div>
</div>
<p>The&nbsp;<code>varImp</code>&nbsp;function is used to help identify which predictors are contributing most to the predictions made by your model. From the result, cane has the highest importance score suggesting it s the most influential variable in the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="st">"Odds ratio"</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(model_log)),<span class="dv">4</span>), </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>      <span class="st">"P-value"</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">coef</span>(<span class="fu">summary</span>(model_log)),<span class="dv">4</span>)[,<span class="dv">4</span>], </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">confint.default</span>(model_log, <span class="at">level =</span> <span class="fl">0.95</span>)),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Odds ratio P-value  2.5 %       97.5 %
(Intercept)     0.0054  0.7370 0.0000 8.949811e+10
Cane           10.9150  0.0351 1.1823 1.007648e+02
Diameter        0.0010  0.1607 0.0000 1.546670e+01
Height          2.3119  0.8992 0.0000 9.934237e+05</code></pre>
</div>
</div>
<p>Cane has an odd ratio of 10.91. This implies that for each unit increase in cane, the odds of the outcome are approximately 10.91 times higher, with a P-value of 0.0351 indicates it is statistically significant (evidence to suggest Cane has a meaningful effect on the outcome).</p>
<p>Diameter has an odd ratio of 0.0010. This indicate that for each unit increase in diameter, the odds of the choice of seedling made decrease significantly (close to zero).With a P-value of 0.1607 shows it is not statistically significant.</p>
<p>Height has an odd ratio of 2.3119, implying that for each unit increase in height, the odds of the choice of seedling made are increased by about 2.31 times. With a p-value(0.8992). It shows it is not statistically significant.</p>
<p>Hence, we can say that cane is a significant predictor of the choice of seedlings.</p>
</section>
</section>
</section>
<section id="multinomial-logistic-regression" class="level1">
<h1><span style="color: #234F1E;"><strong>Multinomial Logistic Regression</strong></span></h1>
<p>Multinomial logistic regression (often just called “multinomial regression”) is used to predict a nominal dependent variable given one or more independent variables. Multinomial logistic regression is used when the dependent variable has more than two categories.</p>
<p>The equation for multinomial logistic regression is as shown below:</p>
<p>Let K be the number of possible outcomes.</p>
<p>Let P(Y=k|X) be the probability of outcome k given predictors X.</p>
<p>Let <span class="math inline">\(\beta_{kj}\)</span> be the coefficient for predictor j in predicting outcome k</p>
<p>Then, the probability of outcome k is given by:</p>
<p><span class="math display">\[P(Y=k|X) = \frac{\exp(\beta_{ko} + beta_{k1*X1} + ... + (\beta_{kp*Xp})}{\sum(exp(β_{j0} + β_{j1*X1} + ... + β_{jp*Xp}))}\]</span></p>
<p><span class="math inline">\(β_{ko}\)</span> is the intercept for outcome k.</p>
<p>The summation in the denominator is over all possible outcomes j.</p>
<p><strong>Interpretation</strong></p>
<p>The formula calculates the probability of each possible outcome given the values of the predictor variables.</p>
<p>The coefficients (β values) represent the impact of the predictors on the log-odds of each outcome compared to a reference category.</p>
<p>Y= <span class="math inline">\(\beta_0\)</span> + <span class="math inline">\(\beta_1X_1\)</span> + <span class="math inline">\(\beta_2X_2\)</span> + … + <span class="math inline">\(\beta_kX_k\)</span></p>
<p>Where Y = Dependent variables (Odd ratio)</p>
<p><span class="math inline">\(\beta_0\)</span> = Constant</p>
<p><span class="math inline">\(\beta_1\)</span> = Coefficient of variable</p>
<p><span class="math inline">\(X_1\)</span> = Independent variables</p>
<p>E = Error Term</p>
<section id="example-1" class="level2">
<h2 class="anchored" data-anchor-id="example-1"><span style="color: #002D62;">Example</span></h2>
<p>To predict the species of new flowers using a multinomial logistic regression model fitted on the iris dataset.This loads the library and the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet) </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(iris) </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit multinomial logistic regression model </span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">multinom</span>(Species <span class="sc">~</span> Petal.Length </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span> Petal.Width </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span> Sepal.Length </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">+</span> Sepal.Width, </span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> iris) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  18 (10 variable)
initial  value 164.791843 
iter  10 value 16.177348
iter  20 value 7.111438
iter  30 value 6.182999
iter  40 value 5.984028
iter  50 value 5.961278
iter  60 value 5.954900
iter  70 value 5.951851
iter  80 value 5.950343
iter  90 value 5.949904
iter 100 value 5.949867
final  value 5.949867 
stopped after 100 iterations</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Predict flower species for new data </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>new_flo <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Petal.Length =</span> <span class="fl">1.5</span>, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Petal.Width =</span> <span class="fl">0.3</span>,  </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Sepal.Length =</span> <span class="fl">4.5</span>,  </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">Sepal.Width =</span> <span class="fl">3.1</span>) </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model, <span class="at">newdata =</span> new_flo, <span class="at">type =</span> <span class="st">"class"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] setosa
Levels: setosa versicolor virginica</code></pre>
</div>
</div>
<p>When the&nbsp;<code>predict()</code>&nbsp;function is executed with the new data, it returns the species of the iris flower based on the provided measurements. The output is a predicted class label, which tells us that the <code>new_flo</code> belongs to setosa specie according to the fitted model.</p>
<p><br><br></p>
</section>
</section>
<section id="ordinal-logistic-regression" class="level1">
<h1><span style="color: #234F1E;"><strong>Ordinal Logistic Regression</strong></span></h1>
<p>Ordinal logistic regression or (ordinal regression) is used to model the relationship between <strong>an ordinal response variable</strong> and <strong>one or more explanatory variables</strong>. It is used to predict an <strong>ordinal dependent variable</strong> given <strong>one or more independent variables</strong>. The explanatory variables may be either continuous or categorical. We explore how one or more independent variables relate to the probability of an ordinal outcome being categorized into a specific or higher category using ordinal logistic regression.</p>
<p>Ordinal Logistic Regression has assumptions which varies from the general logistic regression. They are listed below:</p>
<p><strong>Assumptions</strong></p>
<p>• The dependent variable is measured on an ordinal level.</p>
<p>• One or more of the independent variables are either continuous, categorical or ordinal.</p>
<p>• No multi-collinearity - i.e.&nbsp;when two or more independent variables are highly correlated with each other.</p>
<p>• Proportional Odds - i.e.&nbsp;that each independent variable has an identical effect at each cumulative split of the ordinal dependent variable.</p>
<p><strong>Ordinal Regression Model:</strong></p>
<p><span class="math display">\[logit(P(Y \geq j)) = \beta_{jo} + \beta_1x_1 + ...+ \beta_px_p\]</span> Where:</p>
<p><span class="math inline">\(P(Y \geq j)\)</span> = the cummulative probability of the response variable within category j</p>
<p><span class="math inline">\(\beta_{jo}\)</span> = the threshold parameter for category j</p>
<p><span class="math inline">\(\beta_{1}\)</span>, <span class="math inline">\(\beta_2\)</span>, …, <span class="math inline">\(\beta_{jp}\)</span> are model coefficient associated with the predictor variables <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span>, …, <span class="math inline">\(X_p\)</span></p>
<section id="example-2" class="level2">
<h2 class="anchored" data-anchor-id="example-2"><span style="color: #002D62;">Example</span></h2>
<ul>
<li>Let’s use a hypothetical dataset where we predict customer satisfaction (ordinal variable: Low, Medium, High) based on factors like age, income, and product usage.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ordinal)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulated data (replace with your actual data)</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">satisfaction =</span> <span class="fu">factor</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Medium"</span>, <span class="st">"High"</span>), <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">age =</span> <span class="fu">sample</span>(<span class="dv">25</span><span class="sc">:</span><span class="dv">65</span>, <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">income =</span> <span class="fu">sample</span>(<span class="dv">30000</span><span class="sc">:</span><span class="dv">100000</span>, <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">usage =</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>, <span class="dv">100</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  satisfaction age income usage
1         High  47  73927     2
2         High  39  36600     4
3         High  45  87700     5
4       Medium  61  83517     2
5         High  32  82352     3
6       Medium  34  96153     3</code></pre>
</div>
</div>
<p>This shows the data we will be using for this analysis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(data)) <span class="co">#checking for missing values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  4 variables:
 $ satisfaction: Ord.factor w/ 3 levels "High"&lt;"Low"&lt;"Medium": 1 1 1 3 1 3 3 3 1 2 ...
 $ age         : int  47 39 45 61 32 34 58 34 46 36 ...
 $ income      : int  73927 36600 87700 83517 82352 96153 77801 61516 96074 62262 ...
 $ usage       : int  2 4 5 2 3 3 1 3 2 3 ...</code></pre>
</div>
</div>
<p>From here, we can see the sum of missing data and also the structure of the data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Logistic-Regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the image above, we can view the relationship between the four variables. Satisfaction and other variables indicate weak linear relationship, age appears more spread out across income and usage, while income is more continuous and could be spread across age and usage whereas, usage is discrete( limited set of values) due to its clear horizontal bands.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the ordinal logistic regression model</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ordinal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ordinal'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    slice</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">clm</span>(satisfaction <span class="sc">~</span> age <span class="sc">+</span> usage , <span class="at">data =</span> data)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: satisfaction ~ age + usage
data:    data

 link  threshold nobs logLik  AIC    niter max.grad cond.H 
 logit flexible  100  -108.48 224.95 3(0)  5.13e-08 9.5e+04

Coefficients:
      age     usage 
-0.005358  0.206033 

Threshold coefficients:
  High|Low Low|Medium 
   -0.2749     1.1276 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of the model</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>formula: satisfaction ~ age + usage
data:    data

 link  threshold nobs logLik  AIC    niter max.grad cond.H 
 logit flexible  100  -108.48 224.95 3(0)  5.13e-08 9.5e+04

Coefficients:
       Estimate Std. Error z value Pr(&gt;|z|)
age   -0.005358   0.017546  -0.305    0.760
usage  0.206033   0.129595   1.590    0.112

Threshold coefficients:
           Estimate Std. Error z value
High|Low    -0.2749     0.8794  -0.313
Low|Medium   1.1276     0.8869   1.271</code></pre>
</div>
</div>
<ol type="1">
<li><p><strong>Age</strong> is not a significant predictor of satisfaction (p = 0.76), indicating that <strong>age</strong> doesn’t have a substantial effect on satisfaction levels in this model.</p></li>
<li><p><strong>Usage</strong> has a positive effect on satisfaction, but the relationship is not statistically significant at the 5% level (p = 0.112). This suggests that <strong>usage</strong> might have some influence on satisfaction, but the evidence is not strong enough to claim a significant effect in this model.</p></li>
<li><p>The <strong>thresholds</strong> describe the boundaries between the different levels of satisfaction, but they are not significantly different from zero, meaning there may not be clear boundaries between the categories in this model.</p></li>
</ol>
<p>Summarily, neither predictor (<strong>age</strong> or <strong>usage</strong>) appears to significantly impact the ordinal outcome variable <strong>satisfaction</strong> based on this model’s result</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>